[plugin-mobile-app] Add step to upload file to a device
vividus-framework/vividus pull request #1000
Opened 2020-10-07 14:29 UTC by uarlouski

2020-10-07 14:55 UTC, ikalinin1 approved these changes

2020-10-07 14:58 UTC, valfirst requested changes

2020-10-07 14:58 UTC, valfirst commented on docs/modules/plugins/pages/plugin-mobile-app.adoc
> +|`mobile-application.device-folder`
`mobile-environment.device.folder-for-file-uploading`

2020-10-07 14:58 UTC, valfirst commented on vividus-plugin-mobile-app/build.gradle
> +     testCompile(group: 'com.github.spotbugs', name: 'spotbugs-annotations', version: spotbugsVersion)
`testCompileOnly`

2020-10-07 14:58 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/resources/org/vividus/mobileapp/action/data.txt
> +:)
what for?

2020-10-07 14:58 UTC, valfirst commented on vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
> +Meta: @targetPlatform android
```
Meta:
    @targetPlatform android
```

2020-10-07 14:58 UTC, valfirst commented on vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
> +Meta: @targetPlatform ios
```
Meta:
    @targetPlatform ios
```

2020-10-07 15:17 UTC, uarlouski commented on vividus-plugin-mobile-app/src/main/resources/org/vividus/mobileapp/action/data.txt
> +:)
moved to test package

2020-10-08 06:03 UTC, valfirst approved these changes

2020-10-08 08:15 UTC, merged