[vividus] Add while-like step
vividus-framework/vividus pull request #1002
Opened 2020-10-08 15:17 UTC by ikalinin1

2020-10-08 15:29 UTC, valfirst requested changes

2020-10-08 15:29 UTC, valfirst commented on docs/modules/commons/nav.adoc
>  * xref:tests-configuration.adoc[Tests Configuration]
lets move it outside commons

2020-10-08 15:29 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +Here one could find description of the steps that delivered with Vividus itself without any plugins required.
`that are delivered`

2020-10-08 15:29 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +Executes steps while condition or iteration limit reached.
`while` -> `until`

2020-10-08 15:29 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +If iteration limit reached no failure or exception will happen
`is reached`

2020-10-08 15:29 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +If iteration limit reached no failure or exception will happen
`happen` -> `occur`

2020-10-08 15:29 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +. `$max` - iterations
please elaborate

2020-10-08 15:29 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +When I execute steps at most $max times while `$variableName` is $comparisonRule `$expectedValue`:$stepsToExecute
```
... while variable '$name' is $comparisonRule...
```
lets make variable reference more explicit

2020-10-08 15:29 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +. `$variableName` - variable name to check
a name of the variable to check

2020-10-08 15:29 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> -
noisy change

2020-10-08 15:29 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +When I execute steps at most $max times while `$variableName` is $comparisonRule `$expectedValue`:$stepsToExecute
I think we need to document alias as well

2020-10-08 15:29 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/steps/ExecutableSteps.java
> +    private boolean variableValueFits(String name, Matcher<String> verifier)
`doesVariableValueMatch`

2020-10-08 15:29 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/steps/ExecutableSteps.java
> +        return verifier.matches(variable);
```java
return variable == null || verifier.matches(variable);
```

2020-10-09 07:59 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +When I execute steps at most $max times while `$variableName` is $comparisonRule `$expectedValue`:$stepsToExecute
@ikalinin1 ☝️

2020-10-09 09:22 UTC, valfirst approved these changes

2020-10-09 14:45 UTC, uarlouski approved these changes

2020-10-09 20:15 UTC, merged