Add SauceLabs web/phone/iphone profile
vividus-framework/vividus pull request #1013
Opened 2020-10-12 09:17 UTC by TatianaTochko

2020-10-12 09:43 UTC, valfirst requested changes

2020-10-12 09:43 UTC, valfirst commented on .github/workflows/gradle.yml
> +        done
invalid usage

2020-10-12 09:43 UTC, valfirst commented on .github/workflows/gradle.yml
> +                               -Pvividus.configuration.suite= \
use `grid` suite

2020-10-12 09:43 UTC, valfirst commented on .github/workflows/gradle.yml
> +                               -Pvividus.bdd.story-loader.batch-1.resource-include-patterns=ProxyStepsTests.story \
2 properties above are not needed

2020-10-12 13:19 UTC, valfirst requested changes

2020-10-12 13:19 UTC, valfirst commented on .github/workflows/gradle.yml
> +      - master
please remove all noisy (whitespace-only) changes

2020-10-14 10:07 UTC, closed without merging

2020-10-14 10:08 UTC, TatianaTochko commented
Remove changes to https://github.com/vividus-framework/vividus/pull/1023