[extension-selenium] Add step to check element existence for duration
vividus-framework/vividus pull request #1034
Opened 2020-10-16 15:11 UTC by uarlouski

2020-10-17 20:13 UTC, valfirst requested changes

2020-10-17 20:13 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/GenericWaitSteps.java
> +    @Then("element located '$locator' exists for '$duration' duration")
```
Then element located `$locator` exists for `$duration` duration
```

2020-10-17 20:13 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/GenericWaitSteps.java
> +                locator, duration.toSeconds()), result.isWaitPassed());
is there any way to pretty-print duration?

2020-10-17 20:13 UTC, valfirst commented on vividus-extension-selenium/src/test/java/org/vividus/bdd/steps/ui/GenericWaitStepsTests.java
> +        verify(softAssert).assertFalse("Element located by locator ' Search: 'value'; Visibility: VISIBLE;' has existed"
I believe we should revise `org.vividus.ui.action.search.Locator#toString` as first

2020-10-17 20:50 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/WaitSteps.java
> +    @Deprecated(forRemoval = true, since = "0.3.0")
`since = "0.2.9"`

2020-10-19 07:45 UTC, ikalinin1 approved these changes

2020-10-19 13:12 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/GenericWaitSteps.java
> +            durationFormat += "s' seconds' ";
what about adding minutes as well?

2020-10-19 13:13 UTC, valfirst requested changes

2020-10-19 13:13 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/GenericWaitSteps.java
> +        String assertionMessage = String.format("Element located by locator %s has existed during %s",
`during` vs `for`?

2020-10-20 08:48 UTC, ikalinin1 approved these changes

2020-10-21 12:36 UTC, valfirst approved these changes

2020-10-21 12:37 UTC, merged