[vividus] Add fail fast for known issue
vividus-framework/vividus pull request #1062
Opened 2020-10-23 15:11 UTC by uarlouski

2020-10-23 16:16 UTC, valfirst requested changes

2020-10-23 16:16 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +== Fail Fast
this section should go after the known issues

2020-10-23 16:16 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +|soft-assert.known-issue-fail-fast
`soft-assert.fail-fast-on-known-issue`

2020-10-23 16:16 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +|Skip the rest of scenario in case of known issue
`in case of failure with the known issue`

2020-10-23 16:16 UTC, valfirst commented on vividus/src/main/java/org/vividus/softassert/AssertionManager.java
> +    private boolean knownIssueFailFast;
I believe it would be better to have the ability to specify which known-issue should fail-fast scenario and which shouldn't

2020-11-02 13:34 UTC, valfirst requested changes

2020-11-02 13:34 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +<8> Skip the rest of scenario in case of failure with the known issue
`with the known issue` -> `identified as this known issue`

2020-11-02 13:34 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +<9> Skip the rest of story in case of failure with the known issue
`with the known issue` -> `identified as this known issue`

2020-11-02 13:34 UTC, valfirst commented on vividus-soft-assert/src/test/java/org/vividus/softassert/model/KnownIssueTests.java
> +    {
`@BeforeEach` ?

2020-11-02 13:34 UTC, valfirst commented on vividus/src/main/java/org/vividus/softassert/AssertionManager.java
> +    private final SpringStoryControls springStoryControls;
I believe you can use `org.jbehave.core.embedder.StoryControls`

2020-11-03 07:26 UTC, valfirst approved these changes

2020-11-03 07:43 UTC, ikalinin1 approved these changes

2020-11-03 07:59 UTC, valfirst requested changes

2020-11-03 07:59 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +        "failTestSuiteFast": true <9>
I think we should follow BDD-like approach:
 - `failScenarioFast`
 - `failStoryFast`

2020-11-03 08:28 UTC, valfirst approved these changes

2020-11-03 08:29 UTC, merged