[plugin-web-app] Add possibility to mock browser's HTTP requests
vividus-framework/vividus pull request #1135
Opened 2020-11-13 12:21 UTC by ikalinin1

closes #1104

2020-11-13 12:34 UTC, uarlouski commented on vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java
> +    @When("I initialize $scopes variable `$variableName` with content of file from path `$path`")
maybe 
@When("I initialize $scopes variable `$variableName` with binary content of file from path `$path`")

2020-11-13 14:00 UTC, valfirst requested changes

2020-11-13 14:00 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/ProxyStepsTests.story
> +
remove this line to stick examples to their scenario

2020-11-27 15:28 UTC, valfirst requested changes

2020-11-27 15:28 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +=== `loadResourceAsByteArray`
`loadBinaryResource` ?

2020-11-27 15:28 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +Loads the resource found at the provided path as bytes array. Could be useful for the steps that accepting raw binary data.
`as bytes array` -> `as bytes`

2020-11-27 15:28 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +When I mock HTTP responses with request URL which CONTAINS `frames.html` using response code `200`, content `#{loadResource(page.html)}` and headers:
the example contains invalid expression reference

2020-11-27 15:28 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +When I mock http requests with URL $rule `$url` with response code `$code` and content `$content`:$headers
`...I mock HTTP responses with request URL which...`

2020-11-27 15:28 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +When I mock http requests with URL $rule `$url` with response code `$code` :$headers
`...I mock HTTP responses with request URL which...`

2020-11-27 15:28 UTC, valfirst commented on vividus-tests/src/main/resources/properties/configuration.properties
> +bdd.variables.global.vividus-test-site-url=https://vividus-test-site.herokuapp.com
`configuration.properties` is not the best place to configure global variables

2020-11-27 15:28 UTC, valfirst commented on vividus-tests/src/main/resources/properties/configuration.properties
> +bdd.variables.global.vividus-test-site-url=https://vividus-test-site.herokuapp.com
`vividus-tests/src/main/resources/properties/environment/envinroment.properties` ?

2020-11-27 15:28 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/ProxyStepsTests.story
> +Scenario: Verify step When I mock http requests with URL $rule `$url` with response code `$code` and content `$content`:$headers mocking resource with bytes
please update the step syntax here and below

2020-11-27 15:38 UTC, valfirst requested changes

2020-11-27 15:38 UTC, valfirst commented on vividus-bdd-engine/src/main/java/org/vividus/bdd/expression/IExpressionProcessor.java
>  }
```java
public interface IExpressionProcessor<T>
{
    Optional<T> execute(String expression);
}
```
?

2020-11-27 15:38 UTC, valfirst commented on vividus-bdd-engine/src/main/java/org/vividus/bdd/expression/IExpressionProcessor.java
>  }
and in this case if you keep `UnaryExpressionProcessor` you won't need to change each and every expression processor

2020-11-27 15:38 UTC, valfirst commented on vividus-bdd-engine/src/main/java/org/vividus/bdd/expression/RandomIntExpressionProcessor.java
> +    public Optional<Object> execute(String expression)
`Optional<Integer>` ?

2020-11-27 15:38 UTC, valfirst commented on vividus-bdd-engine/src/main/java/org/vividus/bdd/expression/FunctionalExpressionProcessor.java
> +public class FunctionalExpressionProcessor implements IExpressionProcessor
I would kept `UnaryExpressionProcessor` as a child of `FunctionalExpressionProcessor `

2020-12-03 09:15 UTC, valfirst approved these changes

2020-12-03 09:25 UTC, uarlouski approved these changes

2020-12-03 11:07 UTC, merged