Clean up
vividus-framework/vividus pull request #1246
Opened 2020-12-17 07:38 UTC by ikalinin1

2020-12-17 07:44 UTC, valfirst requested changes

2020-12-17 07:44 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/SetContextSteps.java
> -                String.format("An element with the name '%1$s'", name),
known issues might be broken here, I propose to keep the commit, but postpone it till `0.3.0`

2020-12-17 07:44 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/SetContextSteps.java
> -                String.format(AN_ELEMENT_WITH_THE_ATTRIBUTE, attributeType, attributeValue),
known issues might be broken here, I propose to keep the commit, but postpone it till `0.3.0`

2020-12-17 07:44 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/SetContextSteps.java
> -        WebElement element = baseValidations.assertIfElementExists(String.format(AN_ELEMENT_WITH_THE_ATTRIBUTE,
known issues might be broken here, I propose to keep the commit, but postpone it till `0.3.0`

2020-12-17 10:59 UTC, valfirst approved these changes

2020-12-18 13:44 UTC, uarlouski commented on vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/WebElementsSteps.java
> +    private boolean verifyText(String regex, String actualText, boolean isWebElement)
isWebElement -> webElement :)

2020-12-18 13:44 UTC, uarlouski approved these changes

2020-12-18 14:07 UTC, merged