1252
vividus-framework/vividus pull request #1266
Opened 2020-12-22 20:16 UTC by ikalinin1

2020-12-22 20:53 UTC, uarlouski commented on vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/PageSteps.java
> +                    pageStates.get("after"));
use lazy logging

2020-12-22 20:54 UTC, uarlouski commented on vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/PageStepsTests.java
> +        verifyNoMoreInteractions(setContextSteps, navigateActions, javascriptActions, uiContext);
inOrder.verifyNoMoreInteractions should work

2020-12-23 06:45 UTC, valfirst requested changes

2020-12-23 06:45 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +Loads given URL in a new table
`table` -> `tab`

2020-12-23 06:45 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +* `$URL` - An URL to navigate to
`The URL to open`

2020-12-23 06:45 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +.OpenDocsInANewTab.story
`.Open docs in a new tab.story`

2020-12-23 06:45 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +When I step page loading
`step` -> `stop`

2020-12-23 06:45 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +.OpenDocsInANewTab.story
`Stop page loading.story`

2020-12-23 06:45 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +When I step page loading
`step` -> `stop`

2020-12-23 06:45 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/WebJavascriptActions.java
> +          + "return result;");
```js
let before = document.readyState;
window.stop();
return {before: before, after: document.readyState};
```
?

2020-12-23 06:45 UTC, valfirst commented on vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/PageStepsTests.java
> +        InOrder inOrder = Mockito.inOrder(setContextSteps, navigateActions, javascriptActions, uiContext);
`inOrder` -> `ordered` (PMD doesn't like variables prefixed with `in` and `out`)

2020-12-23 06:45 UTC, valfirst commented on vividus-plugin-web-app/src/test/java/org/vividus/ui/web/action/WebJavascriptActionsTests.java
> +    void testOpenNewTable()
`Table` -> `Tab`

2020-12-23 06:45 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/PageStepsTests.story
> +    @requirementId 1252
`@requirementId 1154; 1252` ?

2020-12-23 10:55 UTC, valfirst requested changes

2020-12-23 10:55 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/PageStepsTests.story
> +    @requirementId 1154; 1252
`1252` -> `1236`

2020-12-23 12:08 UTC, valfirst approved these changes

2020-12-23 12:51 UTC, uarlouski commented on vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/PageStepsTests.java
> +        verifyNoMoreInteractions(javascriptActions);
logger verification is missing :)

2020-12-23 12:51 UTC, uarlouski approved these changes

2020-12-23 13:02 UTC, ikalinin1 commented on vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/PageStepsTests.java
> +        verifyNoMoreInteractions(javascriptActions);
Wow :)

2020-12-23 13:30 UTC, merged