[bdd-engine] Align fail-fast properties
vividus-framework/vividus pull request #1381
Opened 2021-01-25 09:32 UTC by ikalinin1

2021-01-25 10:23 UTC, valfirst requested changes

2021-01-25 10:23 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +|`bdd.batch-<batch-number>.fail-fasle`
`fasle` -> `fast`

2021-01-25 10:23 UTC, valfirst commented on vividus-bdd-engine/src/main/java/org/vividus/bdd/batch/BatchExecutionConfiguration.java
>      private Boolean ignoreFailure;
is it used?

2021-01-25 10:23 UTC, valfirst commented on vividus/src/main/java/org/vividus/configuration/DeprecatedPropertiesHandler.java
> +    private final List<String> keysToFlipBooleanValue;
`Flip` -> `Invert`

2021-02-03 14:10 UTC, valfirst requested changes

2021-02-03 14:10 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/model/Statistic.java
> +    public void increasePassed()
`increaseXXX` -> `incrementXXX`

2021-02-03 14:10 UTC, valfirst commented on vividus/src/main/java/org/vividus/configuration/DeprecatedPropertiesHandler.java
> +    private boolean isDepreacted(String key)
`isDeprecated `

2021-02-03 14:10 UTC, valfirst commented on vividus/src/main/java/org/vividus/configuration/DeprecatedPropertiesHandler.java
> +    private final Map<String, DeprecatedProperty> deprecatedProeprties = new HashMap<>();
`deprecatedProperties `

2021-02-03 14:10 UTC, valfirst commented on vividus/src/main/java/org/vividus/configuration/DeprecatedPropertiesHandler.java
> +        private final Splitter dynamicValue = Splitter.on(Pattern.compile("\\(.+?\\)")).omitEmptyStrings();
move `Pattern.compile("\\(.+?\\)")` to a new constant

2021-02-04 14:57 UTC, ikalinin1 commented on vividus/build.gradle
> +    implementation(group: 'io.qameta.allure', name: 'allure-model', version: versions.allure)
Without it, there is a compilation error. I'll investigate

2021-02-04 14:58 UTC, ikalinin1 commented on vividus/src/main/java/org/vividus/bdd/model/Node.java
> +    private Optional<Boolean> expectedToHaveChildrens = Optional.empty();
I need third state => not set

2021-02-04 20:59 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/model/Node.java
> +    private Optional<Boolean> expectedToHaveChildrens = Optional.empty();
could you please point where "not set" state is used?

2021-02-05 12:03 UTC, ikalinin1 commented on vividus/src/main/java/org/vividus/bdd/model/Node.java
> +    private Optional<Boolean> expectedToHaveChildrens = Optional.empty();
It was inferred to orElse(Boolean.FALSE) :)

2021-02-08 18:34 UTC, closed without merging