[plugin-websocket][draft] Just simple example for further work
vividus-framework/vividus pull request #1434
Opened 2021-02-18 09:58 UTC by uarlouski

2021-02-26 13:34 UTC, valfirst requested changes

2021-02-26 13:34 UTC, valfirst commented on docs/modules/plugins/pages/plugin-websocket.adoc
> +Disconnects an existing websocket. All the received text messages are kept and can be drained into the variable using the drain step.
`Disconnects from ...`

2021-02-26 13:34 UTC, valfirst commented on vividus-plugin-websocket/src/main/java/org/vividus/bdd/steps/websocket/WebSocketSteps.java
> +        webSocketEndpoints.forEach((k, v) -> this.webSocketEndpoints.put(k, UriUtils.createUri(v)));
don't we have automatic mapping to `Map<String, URI>` ?

2021-02-26 13:34 UTC, valfirst commented on vividus-plugin-websocket/src/main/java/org/vividus/bdd/steps/websocket/WebSocketSteps.java
> +        softAssert.assertThat("Total count of received over WebSocket messages", result, countMatcher);
`"Total count of messages received over WebSocket"`

2021-02-26 13:35 UTC, valfirst commented on vividus-plugin-websocket/build.gradle
> +}
Also please disable publishing till next release

2021-02-26 17:55 UTC, valfirst approved these changes

2021-03-01 08:29 UTC, ikalinin1 commented on vividus-plugin-websocket/build.gradle
> +    implementation(group: 'org.eclipse.jetty.websocket', name: 'websocket-client', version: '9.4.36.v20210114')
9.4.38.v20210224 ? :)

2021-03-01 08:38 UTC, ikalinin1 approved these changes

2021-03-01 09:21 UTC, merged