[allure] Add ability to specify multiple endpoins for links
vividus-framework/vividus pull request #1455
Opened 2021-02-24 06:50 UTC by ikalinin1

![image](https://user-images.githubusercontent.com/17816729/108958847-9efbe100-7684-11eb-80b1-b8b4ff138c8e.png)

![image](https://user-images.githubusercontent.com/17816729/108958902-acb16680-7684-11eb-9290-69b844e41861.png)

![image](https://user-images.githubusercontent.com/17816729/108959252-35300700-7685-11eb-83dd-6be00c08685f.png)

![image](https://user-images.githubusercontent.com/17816729/108959349-585ab680-7685-11eb-9ede-17c9a482eb97.png)

2021-02-24 09:24 UTC, uarlouski commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +. Configure link patterт via properties
patterт -> pattern

2021-02-24 09:35 UTC, valfirst requested changes

2021-02-24 09:35 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +|Metatag
`Meta tag`

2021-02-24 09:35 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +Scenario: Should check variables equals
`equal`

2021-02-24 09:35 UTC, valfirst commented on vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/VividusLabel.java
> +                .flatMap(e -> Stream.of(StringUtils.split(e.getValue(), ";"))
please, use `org.vividus.bdd.model.MetaWrapper#META_VALUES_SEPARATOR` instead of `;`

2021-02-25 07:35 UTC, valfirst approved these changes

2021-02-25 08:55 UTC, uarlouski approved these changes

2021-02-25 15:43 UTC, merged