1421
vividus-framework/vividus pull request #1470
Opened 2021-03-02 11:48 UTC by ikalinin1

closes #1421

2021-03-02 15:33 UTC, valfirst requested changes

2021-03-02 15:33 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/StatisticsStoryReporter.java
> +    public static Map<NodeType, Statistic> statistics()
`getStatistics` - to keep naming consistency

2021-03-02 15:33 UTC, valfirst commented on vividus/src/main/java/org/vividus/report/MetadataLogger.java
> +    public static void banner()
`logBanner`, showBanner`, ...

2021-03-02 15:33 UTC, valfirst commented on vividus/src/main/resources/banner.vividus
> +           █       █           █       █ █     ▐              ▐
we need to be more official, see Spring Boot style

2021-03-02 21:19 UTC, valfirst requested changes

2021-03-02 21:19 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/steps/SetupSteps.java
> + * Copyright 2019-2021 the original author or authors.
noisy changes?

2021-03-02 21:19 UTC, valfirst commented on vividus/src/main/java/org/vividus/report/MetadataLogger.java
> +    private static final String HORIZONTAL_SEPARATOR = HYPHEN.repeat(60);
this change is not needed anymore

2021-03-02 21:19 UTC, valfirst commented on vividus/src/main/java/org/vividus/report/MetadataLogger.java
> +    private static void logFormatted(Consumer<Formatter> formatting)
it doesn't bring value now

2021-03-03 11:06 UTC, uarlouski approved these changes

2021-03-03 11:12 UTC, valfirst requested changes

2021-03-03 11:12 UTC, valfirst commented on vividus/src/main/java/org/vividus/report/MetadataLogger.java
> +                    message.format(CATEGORY_FORMAT, HYPHEN.repeat(HORIZONTAL_RULE_LENGTH), category.getCategoryName());
move `HYPHEN.repeat(HORIZONTAL_RULE_LENGTH)` to a local variable (to generate it onc)

2021-03-04 18:58 UTC, merged