[docs] Document story prioritization feature
vividus-framework/vividus pull request #1471
Opened 2021-03-02 15:03 UTC by uarlouski

2021-03-02 15:27 UTC, valfirst requested changes

2021-03-02 15:27 UTC, valfirst commented on docs/modules/commons/nav.adoc
> +* xref:story-prioritization.adoc[Story Prioritization]
I think it doesn't make sense to have a separate page, just put the content to Configuration page

2021-03-02 21:13 UTC, valfirst approved these changes

2021-03-03 08:32 UTC, ikalinin1 approved these changes

2021-03-03 09:04 UTC, merged