Add wait step for debug purposes
vividus-framework/vividus pull request #1493
Opened 2021-03-15 14:26 UTC by abudevich

Closes #1474

2021-03-15 14:31 UTC, valfirst requested changes

2021-03-15 14:31 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/WaitSteps.java
> +    public void waitForDebug(Duration period)
please move this step to `vividus` module

2021-03-15 14:31 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +Always fails by using
`Always fails by using` -> `The step will wait and fail on purpose`

2021-03-15 14:35 UTC, ikalinin1 commented on vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/WaitSteps.java
> +    public void waitForDebug(Duration period)
I don't think plugin-web-app is a correct place for the step, it could be used outside web context

2021-03-15 14:35 UTC, ikalinin1 commented on vividus-plugin-web-app/src/test/java/org/vividus/bdd/steps/ui/web/WaitStepsTests.java
> +        waitSteps.waitForDebug(TIMEOUT);
make verification ordered

2021-03-15 15:22 UTC, valfirst requested changes

2021-03-15 15:22 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/steps/DebugSteps.java
> +    @Inject private ISoftAssert softAssert;
use constructor-based injection

2021-03-15 15:22 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +. `$period` - total waiting time according to ISO 8601 standard
```
. `$period` - total duration to wait in {iso-date-format-link} format
```

2021-03-15 15:22 UTC, valfirst commented on vividus/src/test/java/org/vividus/bdd/steps/DebugStepsTests.java
> +        verify(softAssert).recordFailedAssertion("Use this step for debug purposes only");
add `Sleeper` verification, example: https://github.com/vividus-framework/vividus/blob/f0118333dab0b76be7f3f5556425d79609bf8abf/vividus/src/test/java/org/vividus/runner/VividusInitializationCheckerTests.java#L54-L63

2021-03-16 06:39 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +----
the documentation should be moved to `vividus-steps.adoc`

2021-03-17 15:24 UTC, uarlouski approved these changes

2021-03-17 15:24 UTC, ikalinin1 commented on docs/modules/commons/pages/vividus-steps.adoc
> +=== Wait for debug
Wait for period? 
....
[WARNING]
the step is for debugging purpose only?

2021-03-17 15:26 UTC, ikalinin1 commented on vividus/src/main/java/org/vividus/bdd/steps/DebugSteps.java
> +    @When("I wait `$period` for debug")
could you please add an integration test?

2021-03-17 15:30 UTC, uarlouski commented on vividus/src/main/java/org/vividus/bdd/steps/DebugSteps.java
> +    private ISoftAssert softAssert;
final

2021-03-17 15:31 UTC, uarlouski commented on vividus/src/main/java/org/vividus/bdd/steps/DebugSteps.java
> +     * Waits <b>period</b> and fail on purpose
fails

2021-03-18 09:27 UTC, ikalinin1 approved these changes

2021-03-18 09:33 UTC, valfirst approved these changes

2021-03-18 11:18 UTC, merged