[vividus-plugin-azure-functions] Introduce Azure Functions support
vividus-framework/vividus pull request #1497
Opened 2021-03-17 20:47 UTC by ikalinin1

2021-03-18 04:58 UTC, valfirst requested changes

2021-03-18 04:58 UTC, valfirst commented on docs/modules/plugins/pages/azure.adoc
> +Vividus provides set of plugin to interact with the services.
`plugins`

2021-03-18 04:58 UTC, valfirst commented on docs/modules/plugins/pages/plugin-azure-functions.adoc
> +The plugin provides functionality to interact with https://azure.microsoft.com/en-us/services/functions/.
`https://azure.microsoft.com/en-us/services/functions/[Azure Functions]`

2021-03-18 04:58 UTC, valfirst commented on docs/modules/plugins/pages/plugin-azure-functions.adoc
> +By default, plugin's authentication depends on correct configure of following environment variables.
`plugin's authentication depends on correct configure of following environment variables` ->
`authentication process relies on the configuration of the following environment variables`

2021-03-18 04:58 UTC, valfirst commented on docs/modules/plugins/pages/plugin-azure-functions.adoc
> +. `AZURE_SUBSCRIPTION_ID` - Azure subscription ID
Do all of them are needed? Or maybe we can define groups of variables specifying different authentication approaches

2021-03-18 04:58 UTC, valfirst commented on docs/modules/plugins/pages/plugin-azure-functions.adoc
> +See the official https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/identity/azure-identity["Azure identity"] guide to get more details.
`https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/identity/azure-identity#environment-variables["Azure identity"]`

2021-03-18 04:58 UTC, valfirst commented on docs/modules/plugins/pages/plugin-azure-functions.adoc
> +When I trigger azure `$functionApp` function app `$function` function in resource group `$resourceGroup` with payload:$payload and save response into `$scopes` variable `$variableNames`
```
When I trigger azure `$functionApp` function app with `$function` function name ...
``` ?

2021-03-18 04:58 UTC, valfirst commented on vividus-plugin-azure-functions/src/main/java/org/vividus/azure/functions/service/FunctionService.java
> +        createManager(responseCapturingHttpPipelinePolicy)
is app service manager thread safe? does it make sense to make it class field?

2021-03-22 07:44 UTC, uarlouski commented on docs/modules/plugins/pages/plugin-azure-functions.adoc
> +* `$payload` - The JSON payload to send to a function(could be empty)
nction (could be empty)

2021-03-22 07:44 UTC, uarlouski commented on docs/modules/plugins/pages/plugin-azure-functions.adoc
> +* `$functionAppName` - the name of the funciton app
funciton :)

2021-03-22 09:01 UTC, valfirst requested changes

2021-03-22 09:01 UTC, valfirst commented on docs/modules/plugins/pages/plugin-azure-functions.adoc
> +* `$variableName` - The variable name to store results in JSON format.
please document what is saved into the variable (statusCode, body, etc.)

2021-03-22 10:56 UTC, abudevich commented on vividus-plugin-azure-functions/src/main/java/org/vividus/azure/functions/steps/FunctionSteps.java
> +     * @param functionApp   the name of Azure Function App. The value can be retrieved by looking
Capital letter for description of parameters ? (as https://github.com/vividus-framework/vividus/blob/0943965b8db6c321acf89223946ff1b3a42af7fb/vividus-plugin-azure-functions/src/main/java/org/vividus/azure/functions/steps/FunctionSteps.java#L56)

2021-03-23 11:55 UTC, valfirst approved these changes

2021-03-23 12:08 UTC, uarlouski approved these changes

2021-03-23 12:59 UTC, merged