[WIP] [plugin-json] Add patch json file step
vividus-framework/vividus pull request #1499
Opened 2021-03-18 15:15 UTC by EDbarvinsky

resolves #1476

2021-03-18 15:16 UTC, EDbarvinsky commented on vividus-plugin-json/build.gradle
> +    implementation (group: 'net.javacrumbs.json-unit', name: 'json-unit', version: '2.18.0')
Have tried to get rid of this dependencies, but do not succeed. Will discuss tomorrow

2021-03-19 07:38 UTC, valfirst requested changes

2021-03-19 07:38 UTC, valfirst commented on vividus-plugin-json/src/main/java/org/vividus/bdd/steps/json/JsonSteps.java
> +public class JsonSteps
`JsonPatchSteps`

2021-03-19 07:38 UTC, valfirst commented on vividus-plugin-json/src/main/java/org/vividus/bdd/steps/json/JsonSteps.java
> +            + " variable with name '$pathVariable'")
```
When I patch JSON `$sourceJson` using `$jsonPatch` and save result to $scopes variable `$variableName`
```

2021-03-19 14:30 UTC, valfirst requested changes
Please add:
- regular docs (see `/docs` folder)
- integration tests

2021-03-19 14:30 UTC, valfirst commented on vividus-plugin-json/build.gradle
> +    implementation (group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.12.2')
do you really need it?

2021-03-19 14:30 UTC, valfirst commented on vividus-plugin-json/src/main/java/org/vividus/bdd/steps/json/JsonPatchSteps.java
> +        JsonMapper jsonMapper = new JsonMapper();
is it thread safe? if so, it should be a field of class

2021-03-19 14:30 UTC, valfirst commented on vividus-plugin-json/src/main/java/org/vividus/bdd/steps/json/JsonPatchSteps.java
> +    @When("I patch JSON `$sourceJson` using `$jsonPatch` and save result to $scopes variable `$variableName`")
please add javadocs

2021-03-22 08:15 UTC, ikalinin1 commented on settings.gradle
> +include 'vividus-plugin-json'
I believe we follow alphabetical order here

2021-03-22 08:18 UTC, ikalinin1 commented on vividus-plugin-json/src/main/java/org/vividus/bdd/steps/json/JsonPatchSteps.java
> +    @When("I patch JSON `$sourceJson` using `$jsonPatch` and save result to $scopes variable `$variableName`")
and documentation

2021-03-23 08:04 UTC, ikalinin1 approved these changes

2021-03-23 08:05 UTC, valfirst requested changes

2021-03-23 08:05 UTC, valfirst commented on docs/modules/plugins/pages/plugin-json.adoc
> += Json Plugin
let's use `JSON` notation everywhere

2021-03-23 08:05 UTC, valfirst commented on docs/modules/plugins/pages/plugin-json.adoc
> +* `$sourceJson` - JSON file to be patched.
it's not file, but JSON data

2021-03-23 08:05 UTC, valfirst commented on docs/modules/plugins/pages/plugin-json.adoc
> +* `$jsonPatch` - JSON file with required patch actions according to https://tools.ietf.org/html/rfc6902#page-6[RFC-6902]
not file, similar to the above comment

2021-03-23 08:05 UTC, valfirst commented on docs/modules/plugins/pages/plugin-json.adoc
> +* `$scopes` - xref:parameters:variable-scope.adoc[the comma-separated set of the variables scopes]
`The`

2021-03-23 08:05 UTC, valfirst commented on vividus-plugin-json/src/main/java/org/vividus/bdd/steps/json/JsonPatchSteps.java
> +     * @param jsonPatch json file with patch actions
please see related comments for the documentation

2021-03-23 08:05 UTC, valfirst commented on docs/modules/plugins/pages/plugin-json.adoc
> +* `$variableName` - The variable
please add example of using step

2021-03-23 08:05 UTC, valfirst commented on docs/modules/plugins/pages/plugin-json.adoc
> +* `$variableName` - The variable
`The variable name`

2021-03-23 08:41 UTC, valfirst requested changes

2021-03-23 08:41 UTC, valfirst commented on docs/modules/plugins/pages/plugin-json.adoc
> +.Send the data to the Kafka topic
obviously it's about Kafka 😄

2021-03-23 08:43 UTC, valfirst commented on settings.gradle
> +include 'vividus-plugin-json'
also please add the plugin here: https://github.com/vividus-framework/vividus/blob/master/vividus-docker-bundler/build.gradle

2021-03-23 08:45 UTC, valfirst commented on vividus-plugin-json/build.gradle
> +}
also please add these 2 lines here at the end of file:
https://github.com/vividus-framework/vividus/blob/057c1f41cff1b2038b1979bde91b126f0da6e3f6/vividus-plugin-websocket/build.gradle#L16-L17

2021-03-23 10:04 UTC, valfirst approved these changes

2021-03-23 11:52 UTC, uarlouski approved these changes

2021-03-23 12:27 UTC, merged