[plugin-azure-storage-blob] Add Azure Blob storage support
vividus-framework/vividus pull request #1533
Opened 2021-04-01 20:19 UTC by ikalinin1

2021-04-02 06:37 UTC, valfirst requested changes

2021-04-02 06:37 UTC, valfirst commented on docs/modules/plugins/pages/plugin-azure-storage-blob.adoc
> +implementation(group: 'org.vividus', name: 'vividus-plugin-azure-storage-blob', version: '{current-version}')
I think we should stick to the naming of Azure services:
`vividus-plugin-azure-storage-account`

Blob storage is a part of storage account functionality

2021-04-02 06:37 UTC, valfirst commented on docs/modules/plugins/pages/plugin-azure-storage-blob.adoc
> +.. `sas-token` - The https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview[SAS token]
Why not to use Azure Active Directory as for other services? SAS token creation could be challenging due to permission restrictions

2021-04-02 06:37 UTC, valfirst commented on docs/modules/plugins/pages/plugin-azure-storage-blob.adoc
> +.. `container` - Comma-separated list of containers
different storage accounts may have containers with same names

2021-04-07 12:47 UTC, uarlouski approved these changes

2021-04-09 08:02 UTC, merged