Wait
vividus-framework/vividus pull request #1549
Opened 2021-04-09 14:14 UTC by ikalinin1

Just testing story

2021-04-12 15:04 UTC, valfirst requested changes

2021-04-12 15:04 UTC, valfirst commented on docs/modules/plugins/pages/plugin-rest-api.adoc
> +When I set number of elements from `$json` found by JSON path `$jsonPath` to $scopes variable `$variableName`
`When I save number ...` - since majority of our steps uses `save`-term

2021-04-12 15:04 UTC, valfirst commented on vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java
> +     *                       <li><b>DRAIN</b> - read the messages and remove them from queue
please update to be in sync with regular docs

2021-04-12 15:04 UTC, valfirst commented on vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java
> +        bddVariableContext.putVariable(scopes, variableName, queueOperation.perform(testContext));
```java
bddVariableContext.putVariable(scopes, variableName, queueOperation.perform(testContext.get(MESSAGES_KEY)));
```

2021-04-12 15:04 UTC, valfirst commented on vividus-tests/src/main/resources/story/system/Kafka.story
> +When I execute steps with delay `PT1S` at most 30 times while variable `messageAppeared` is = `0`:
`messageAppeared` -> `messageCount`

2021-04-13 19:31 UTC, valfirst approved these changes

2021-04-14 08:25 UTC, uarlouski approved these changes

2021-04-14 08:25 UTC, uarlouski commented on docs/modules/plugins/pages/plugin-kafka.adoc
> +* `$queueOperation` -  `DRAIN` - saves the messages consumed since the last drain or from the consumption start and moves the consumer cursor to the position after the last consumed message, `PEEK` -
I think that table for describing operations would be better here

2021-04-14 09:02 UTC, merged