[vividus] Add ability to use variables in templates
vividus-framework/vividus pull request #1550
Opened 2021-04-09 16:41 UTC by uarlouski

2021-04-09 17:32 UTC, valfirst requested changes
Please add docs

2021-04-09 17:34 UTC, valfirst requested changes

2021-04-09 17:34 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java
> +        Map<String, Object> dataModel = bddVariableContext.getVariables();
please update javadocs according to the changes

2021-04-09 19:11 UTC, valfirst requested changes

2021-04-09 19:11 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +It's allowed to use `global`, `scenario`, `story` and other variable types within templates by referring them using the variable reference notation. Note than the parameters passed to the step take p
```
...to use `global`, `scenario`, `story` and other variable types...
```
->
```
...to use `global`, `next batches`, `scenario` and `story` variables...
```

2021-04-09 19:11 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +It's allowed to use `global`, `scenario`, `story` and other variable types within templates by referring them using the variable reference notation. Note than the parameters passed to the step take p
`than` -> `that`

2021-04-09 19:11 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +* `$templateParameters` - The template parameters
add dots `.` to the end of all parameters descriptions

2021-04-09 19:11 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +When I initialize the $scopes variable `age` with value `4510`
` $scopes` -> `scenario`

2021-04-09 19:12 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java
> +     * It's allowed to use <i>global</i>, <i>scenario</i>, <i>story</i> and other variable types within templates
https://github.com/vividus-framework/vividus/pull/1550#discussion_r610850507

2021-04-09 19:12 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java
> +     * by referring them using the variable reference notation. Note than the parameters passed to the step take
https://github.com/vividus-framework/vividus/pull/1550/files#r610850715

2021-04-12 07:28 UTC, valfirst approved these changes

2021-04-12 07:28 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java
> +     * precedence over the variables.
it can be moved to the previous line

2021-04-12 07:40 UTC, ikalinin1 approved these changes

2021-04-12 09:49 UTC, merged