[vividus] Add support for vividus expressions in templates
vividus-framework/vividus pull request #1586
Opened 2021-04-23 16:40 UTC by uarlouski

2021-04-23 16:49 UTC, ikalinin1 commented
@uarlouski  please add integration test

2021-04-23 16:51 UTC, uarlouski commented
> @uarlouski please add integration test

it's draft :)

2021-04-24 11:48 UTC, valfirst requested changes

2021-04-24 11:48 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/steps/FreemarkerSteps.java
> +                                                  .collect(Collectors.joining(",", expressionName + "(", ")"));
what about nested expressions?

2021-04-24 11:48 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/steps/FreemarkerSteps.java
> +            return processors.stream().map(p -> p.execute(expression))
I think it makes sense to use `ExpressionAdaptor` to avoid copy-pasted logic

2021-04-24 14:06 UTC, uarlouski commented on vividus/src/main/java/org/vividus/bdd/steps/FreemarkerSteps.java
> +                                                  .collect(Collectors.joining(",", expressionName + "(", ")"));
how do you imagine it will look like?

2021-04-26 05:01 UTC, uarlouski commented on vividus/src/main/java/org/vividus/bdd/steps/FreemarkerSteps.java
> +                                                  .collect(Collectors.joining(",", expressionName + "(", ")"));
added example

2021-04-26 06:44 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/steps/FreemarkerSteps.java
> +                                                  .collect(Collectors.joining(",", expressionName + "(", ")"));
please update the docs as well

2021-04-27 09:58 UTC, valfirst requested changes

2021-04-27 09:58 UTC, valfirst commented on vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ExpressionAdaptor.java
> +     * Processes the expression including processing nested ones.
`Processes the expression including nested ones.`

2021-04-27 09:58 UTC, valfirst commented on vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ExpressionAdaptor.java
> +     * Processes the expression without processing nested ones.
`Processes the expression excluding nested ones.`

2021-04-27 09:58 UTC, valfirst commented on vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ExpressionAdaptor.java
> +    private Object wrap(String value, Supplier<Object> expressionResolver)
`wrap` -> `processExpression`

2021-04-27 10:20 UTC, ikalinin1 approved these changes

2021-04-27 12:10 UTC, valfirst approved these changes

2021-04-27 12:49 UTC, merged