Partially delete deprecated API from base validations
vividus-framework/vividus pull request #1612
Opened 2021-05-06 09:37 UTC by uarlouski

2021-05-06 10:13 UTC, ikalinin1 approved these changes

2021-05-06 10:19 UTC, valfirst requested changes

2021-05-06 10:19 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/validation/IBaseValidations.java
> -    List<WebElement> assertIfNumberOfElementsFound(String businessDescription, Locator locator, int number,
this removal introduces breaking changes

2021-05-06 15:22 UTC, valfirst approved these changes

2021-05-07 14:51 UTC, ikalinin1 approved these changes

2021-05-07 15:20 UTC, merged