[vividus] Add cartesian product table transformer
vividus-framework/vividus pull request #1624
Opened 2021-05-12 15:03 UTC by uarlouski

2021-05-12 19:53 UTC, valfirst requested changes

2021-05-12 19:53 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/transformer/CartesianProductTableTransformer.java
> +        isTrue(repeatingKeys.isEmpty(), "Tables must contain different keys: %s", repeatingKeys);
`"Tables must contain different keys, but found the same keys: %s"`

2021-05-13 08:21 UTC, uarlouski commented on vividus/src/main/java/org/vividus/bdd/transformer/AbstractTableLoadingTransformer.java
> +    @Inject private Configuration configuration;
it needs to avoid circular deps

2021-05-13 09:54 UTC, valfirst approved these changes

2021-05-14 07:24 UTC, ikalinin1 commented on docs/modules/commons/pages/table-transformers.adoc
> +== CARTESIAN_PRODUCT
Looks like merge mode to me

2021-05-14 07:27 UTC, ikalinin1 commented on docs/modules/commons/pages/table-transformers.adoc
> +== CARTESIAN_PRODUCT
Have you considered adding a new merging mode instead of a new transformer?

2021-05-14 07:51 UTC, ikalinin1 commented on vividus/src/main/java/org/vividus/bdd/transformer/CartesianProductTableTransformer.java
> +        List<List<String>> rightRows = getRows(right);
https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/Lists.java#L373-L429

2021-05-14 08:25 UTC, ikalinin1 approved these changes

2021-05-14 09:06 UTC, valfirst requested changes

2021-05-14 09:06 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/transformer/CartesianProductTableTransformer.java
> +        return ExamplesTable.EMPTY.withRows(examplesTableRows);
it will modify default `EMPTY` table

2021-05-15 06:33 UTC, valfirst approved these changes

2021-05-15 06:34 UTC, merged