Upgrade to jbehave 5.0.0-alpha.11
vividus-framework/vividus pull request #1683
Opened 2021-06-02 11:50 UTC by uarlouski

2021-06-02 19:49 UTC, valfirst requested changes

2021-06-02 19:49 UTC, valfirst commented on vividus-plugin-accessibility/src/main/java/org/vividus/bdd/converter/ParametersToAccessibilityCheckOptionsConverter.java
> +                Set.of());
noisy change

2021-06-02 19:49 UTC, valfirst commented on vividus-plugin-email/src/main/java/org/vividus/bdd/email/converter/StringToListOfMessagePredicatesConverter.java
>  public class StringToListOfMessagePredicatesConverter
`ParametersToMessagePredicateConverter`

2021-06-02 19:49 UTC, valfirst commented on vividus-plugin-email/src/main/java/org/vividus/bdd/email/converter/StringToListOfMessagePredicatesConverter.java
>  public class StringToListOfMessagePredicatesConverter
and do not forget to rename unit tests class

2021-06-02 19:49 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/bdd/converter/ui/web/StringToListSequenceActionConverter.java
> +public class StringToListSequenceActionConverter extends AbstractParameterConverter<Parameters, SequenceAction>
`ParametersToSequenceActionConverter`

2021-06-02 19:49 UTC, valfirst commented on vividus/src/main/java/org/vividus/bdd/converter/ParametersToListOfMapsConverter.java
> +public class ParametersToListOfMapsConverter extends AbstractParameterConverter<Parameters, Map<String, String>>
`ParametersToMapConverter `

2021-06-03 08:02 UTC, uarlouski commented on vividus-plugin-accessibility/src/main/java/org/vividus/bdd/converter/ParametersToAccessibilityCheckOptionsConverter.java
> +                Set.of());
121

2021-06-03 09:18 UTC, valfirst approved these changes

2021-06-04 08:25 UTC, merged