Not equal
vividus-framework/vividus pull request #1707
Opened 2021-06-11 14:11 UTC by ikalinin1

2021-06-11 14:44 UTC, valfirst requested changes

2021-06-11 14:44 UTC, valfirst commented on docs/modules/plugins/pages/plugin-visual.adoc
> +Work the same way as <<_compare_against>> except it checks if actual appearance differs from the baseline.
please, add details how will `acceptable-diff-percentage` work in this case

2021-06-11 14:44 UTC, valfirst commented on vividus-extension-visual-testing/src/main/java/org/vividus/visual/bdd/AbstractVisualSteps.java
> +    protected ISoftAssert softAssert()
```suggestion
    protected ISoftAssert getSoftAssert()
```

2021-06-11 14:44 UTC, valfirst commented on vividus-plugin-visual/src/main/java/org/vividus/visual/VisualSteps.java
> +                }
```suggestion
                return check.getAction() == VisualActionType.ESTABLISH
                                         ? visualTestingEngine. establish(check)                                         
                                         : visualTestingEngine.compareAgainst(check);
```

2021-06-11 14:44 UTC, valfirst commented on vividus-extension-visual-testing/src/main/java/org/vividus/visual/model/VisualActionType.java
> +    COMPARE_NOT_EQUAL
```suggestion
    CHECK_INEQUALITY_AGAINST
```

2021-06-17 08:29 UTC, valfirst requested changes

2021-06-17 08:29 UTC, valfirst commented on vividus-plugin-visual/src/main/java/org/vividus/visual/VisualSteps.java
> +                : OptionalInt.empty();
please fix cover this logic with tests

2021-06-18 07:28 UTC, valfirst approved these changes

2021-06-18 15:01 UTC, uarlouski approved these changes

2021-06-18 15:06 UTC, merged