draft
vividus-framework/vividus pull request #1732
Opened 2021-06-18 11:53 UTC by uarlouski

2021-06-21 09:18 UTC, valfirst requested changes

2021-06-21 09:18 UTC, valfirst commented on vividus-facade-jira/src/main/java/org/vividus/jira/databind/JiraIssueDeserializer.java
> +        return root.path(field).path("name").asText("undefined");
why `"undefined"` ?

2021-06-21 09:18 UTC, valfirst commented on vividus-facade-jira/src/main/java/org/vividus/jira/model/JiraEntity.java
> + * Copyright 2019-2021 the original author or authors.
noisy change

2021-06-21 09:18 UTC, valfirst commented on vividus-facade-jira/src/main/java/org/vividus/jira/model/Project.java
> + * Copyright 2019-2021 the original author or authors.
noisy change

2021-06-21 09:18 UTC, valfirst commented on vividus-facade-jira/src/main/java/org/vividus/jira/model/Version.java
> + * Copyright 2019-2021 the original author or authors.
noisy change

2021-06-21 09:18 UTC, valfirst commented on vividus-soft-assert/src/main/java/org/vividus/softassert/formatter/AssertionFormatter.java
> +        details.put("Type", issue.getType());
do you really need one more map? why not to add these values to string builder explicitly?

2021-06-21 09:18 UTC, valfirst commented on vividus-soft-assert/src/main/java/org/vividus/softassert/issue/IIssueStateProvider.java
> +    class IssueState
convert to external class

2021-06-21 09:18 UTC, valfirst commented on vividus-soft-assert/src/main/java/org/vividus/softassert/issue/IIssueStateProvider.java
>  public interface IIssueStateProvider
```suggestion
public interface IssueStateProvider
```
?

2021-06-21 09:18 UTC, valfirst commented on vividus-soft-assert/src/main/java/org/vividus/softassert/issue/KnownIssueChecker.java
> +    private final Optional<IIssueStateProvider> issueStateProvider;
List ?

2021-06-21 09:18 UTC, valfirst commented on vividus-soft-assert/src/main/java/org/vividus/softassert/model/KnownIssue.java
> +    private final String bts;
Optional ?

2021-06-21 09:18 UTC, valfirst commented on vividus-soft-assert/src/main/java/org/vividus/softassert/model/KnownIssue.java
>          this.failTestSuiteFast = issueIdentifier.isFailTestSuiteFast();
just create a single field `issueIdentifier`?

2021-06-21 11:50 UTC, uarlouski commented on vividus-connector-bts-jira/src/main/java/org/vividus/jira/connector/JiraConfiguration.java
> +    private HttpClientConfig httpConfig = new HttpClientConfig();
Caused by: java.lang.NullPointerException
	at org.vividus.http.client.HttpClientFactory.buildHttpClient(HttpClientFactory.java:53) ~[main/:?]
checked

2021-06-22 12:01 UTC, uarlouski commented
temp close

2021-06-22 12:01 UTC, closed without merging