[bdd-engine] Fix resolution of map references
vividus-framework/vividus pull request #1740
Opened 2021-06-21 13:05 UTC by ikalinin1

2021-06-21 15:38 UTC, valfirst requested changes

2021-06-21 15:38 UTC, valfirst commented on vividus-bdd-engine/src/main/java/org/vividus/bdd/variable/Variables.java
> +                           .orElse(variable);
```suggestion
            return Optional.ofNullable(readFieldSafely(variable, key)).orElse(variable);
```

2021-06-22 06:57 UTC, valfirst approved these changes

2021-06-22 07:20 UTC, uarlouski approved these changes

2021-06-22 08:23 UTC, merged