[plugin-mobile-app] Add ability to set vertical x position for swipe
vividus-framework/vividus pull request #1776
Opened 2021-07-09 13:50 UTC by uarlouski

draft no docs

2021-07-12 11:49 UTC, ikalinin1 commented on vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/model/SwipeDirection.java
> +        Validate.isTrue(percentage >= 0 && percentage <= 100,
please consider this validation at initialization level

2021-07-12 13:18 UTC, valfirst requested changes

2021-07-12 13:18 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/model/SwipeDirection.java
> +        return percentage == 0 ? 1 : (width - 1) * percentage / 100;
if percentage = 0, then result = 1;
if percentage = 100, then result = width - 1;
else result = width * percentage / 100

2021-07-12 13:18 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/TouchActions.java
> +        swipe(new SwipeCoordinates(x, startY, x, endY), swipeDuration);
consider refactoring to avoid duplication

2021-07-12 16:01 UTC, valfirst requested changes

2021-07-12 16:01 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/model/SwipeDirection.java
> +        else if (percentage == 100)
```suggestion
        if (percentage == 100)
```

2021-07-13 04:57 UTC, ikalinin1 approved these changes

2021-07-13 06:36 UTC, valfirst approved these changes

2021-07-13 08:09 UTC, merged