Take screenshots
vividus-framework/vividus pull request #1793
Opened 2021-07-14 13:03 UTC by ikalinin1

2021-07-15 06:32 UTC, valfirst requested changes

2021-07-15 06:32 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +Takes a screenshot to a default screenshot folder defined by property `ui.screenshots.directory`.
```suggestion
Takes a screenshot and saves it to the default folder defined by the property `ui.screenshots.directory`.
```

2021-07-15 06:32 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +Full path to a screenshot will be posted to logs and allure
```suggestion
TIP: The full path to the screenshot is posted to the logs and the report.
```

2021-07-15 06:32 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +Screenshots directory should be defined relatively of project root
is it really required? absolute path is not allowed?

2021-07-15 06:32 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +When I take screenshot
it seems the example is not needed here

2021-07-15 06:32 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +=== Take a screenshot to a path
```suggestion
=== Take a screenshot and save it to the folder
```

2021-07-15 06:32 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +Takes a screenshot to a path defined by user
```suggestion
Takes a screenshot and saves it to the default folder defined by user
```

2021-07-15 06:32 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +Full path to a screenshot will be posted to logs and allure
```suggestion
TIP: The full path to the screenshot is posted to the logs and the report.
```

2021-07-15 06:32 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +When I take screenshot to path `$path`
```suggestion
When I take screenshot and save it to folder `$path`
```

2021-07-15 06:32 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +. `$path` - absolute path to a screenshot file
```suggestion
. `$path` - an absolute or relative path to the folder to save taken screenshot
```

2021-07-15 06:32 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/ScreenshotTakingSteps.java
>      public void whenITakeScreenshotToPath(String path) throws IOException
```suggestion
    public void whenITakeScreenshotToPath(Path path) throws IOException
```

2021-07-15 06:32 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/AbstractScreenshotTaker.java
> +    protected Path takeScreenshotAsFile(Supplier<Path> pathProvider,
```suggestion
    protected Path takeScreenshotAsFile(Path screenshotPath,
```
?

2021-07-15 06:32 UTC, valfirst commented on vividus-tests/src/main/resources/data/tables/mobile_app/start.table
> +!|app |${app-url}|!
please format indents in the table to make it more readable

2021-07-16 09:42 UTC, uarlouski commented on vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/AbstractScreenshotTaker.java
> +            LOGGER.info("Screenshot was taken: {}", screenshotFilePath.toAbsolutePath());
use lazy logging

2021-07-16 09:42 UTC, uarlouski commented on vividus-extension-selenium/src/main/resources/steps/defaults/screenshot.steps
> +When I take screenshot and save it to folder `<path>`
missing eof

2021-07-19 08:11 UTC, valfirst approved these changes

2021-07-19 08:12 UTC, uarlouski approved these changes

2021-07-19 09:17 UTC, merged