Guide for using proxy with docker in pipeline
vividus-framework/vividus pull request #1899
Opened 2021-08-24 12:58 UTC by abudevich

2021-08-24 13:02 UTC, ikalinin1 commented on docs/modules/guides/pages/pipeline-with-proxy.adoc
> += Example of pipeline script with starting VIVIDUS proxy in DOCKER container
Do you mind to put some comments about the sections of the file?

Here is an example 

https://github.com/vividus-framework/vividus/blame/03bfc123f0cd96b32dbd3b6b7f94bcaca3be283a/docs/modules/ROOT/pages/tests-configuration.adoc#L106-L132
![image](https://user-images.githubusercontent.com/17816729/130621041-310b044c-3562-473f-ae6c-77332736883f.png)

2021-08-24 14:31 UTC, valfirst requested changes

2021-08-24 14:31 UTC, valfirst commented on docs/modules/guides/pages/pipeline-with-proxy.adoc
> +```bash
```suggestion
```groovy
```

2021-08-24 14:31 UTC, valfirst commented on docs/modules/guides/pages/pipeline-with-proxy.adoc
> += Example of pipeline script with starting VIVIDUS proxy in DOCKER container
```suggestion
= Jenkins pipeline using browser proxy in Docker container
```

2021-08-24 14:31 UTC, valfirst commented on docs/modules/guides/nav.adoc
> +** xref:pipeline-with-proxy.adoc[Pipeline with proxy]
```suggestion
** xref:pipeline-with-proxy.adoc[Jenkins pipeline with browser proxy]
```

2021-08-24 14:31 UTC, valfirst commented on docs/modules/guides/pages/pipeline-with-proxy.adoc
> +                    [$class: 'RelativeTargetDirectory', relativeTargetDir: "${projectName}"],
please add variable with some dummy value for `${projectName}`

2021-08-25 07:42 UTC, uarlouski commented on docs/modules/guides/pages/pipeline-with-proxy.adoc
> +                userRemoteConfigs: [[credentialsId: "${scmCredentialId}", url: "${gitUrl}"]]])
pass just variable here and in other places

2021-08-25 11:49 UTC, valfirst commented on docs/modules/guides/pages/pipeline-with-proxy.adoc
> +                userRemoteConfigs: [[credentialsId: scmCredentialId, url: gitUrl]]])
how does it work? I am curious about `name: master`, `relativeTargetDir: projectName`, `credentialsId: scmCredentialId, url: gitUrl`

2021-08-25 12:42 UTC, uarlouski approved these changes

2021-08-25 12:54 UTC, valfirst approved these changes

2021-08-25 12:55 UTC, merged