[plugin-mobile-app] Add possibility to swipe the context
vividus-framework/vividus pull request #1939
Opened 2021-09-03 14:52 UTC by ikalinin1

2021-09-03 15:03 UTC, valfirst requested changes

2021-09-03 15:03 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/model/SwipeArea.java
> +public class SwipeArea
`org.openqa.selenium.Rectangle`

2021-09-08 06:55 UTC, valfirst requested changes

2021-09-08 06:55 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/TouchSteps.java
>      public void swipeToElement(SwipeDirection direction, Locator locator, Duration swipeDuration)
does it make sense to update javadocs as well?

2021-09-08 06:56 UTC, valfirst reviewed
Also unit test coverage is below the threshold

2021-09-08 09:38 UTC, valfirst approved these changes

2021-09-08 11:12 UTC, uarlouski approved these changes

2021-09-08 11:21 UTC, merged