Fix known issue validator
vividus-framework/vividus pull request #2024
Opened 2021-09-30 13:37 UTC by ikalinin1

2021-09-30 13:41 UTC, abudevich approved these changes

2021-09-30 14:51 UTC, valfirst requested changes

2021-09-30 15:42 UTC, uarlouski approved these changes

2021-09-30 15:43 UTC, ikalinin1 commented on .github/workflows/gradle.yml
> +                                                             -p vividus-tests
![image](https://user-images.githubusercontent.com/17816729/135487698-86c89e6e-4830-4299-85d6-0b63d027e54e.png)

2021-09-30 15:44 UTC, uarlouski approved these changes

2021-09-30 16:02 UTC, ikalinin1 commented on .github/workflows/gradle.yml
> +         ./gradlew validateKnownIssues printSteps countSteps -x testVividusInitialization \
The case is not working task and it was a regression introduced by the changes, I added the stage to check that tasks are executed successfully and catch such regression

2021-10-01 08:49 UTC, valfirst approved these changes

2021-10-01 08:50 UTC, merged