[extension-selenium] Fix context element rectangle variable
vividus-framework/vividus pull request #2043
Opened 2021-10-04 14:24 UTC by ikalinin1

2021-10-04 15:01 UTC, valfirst requested changes

2021-10-04 15:01 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/bdd/variable/ui/AbstractContextProvidingDynamicVariable.java
> +                            LOGGER.atDebug().log("Unable to get coordinate, context is not set");
```suggestion
                            LOGGER.atError().log("Unable to get coordinate, context is not set");
```

2021-10-04 15:01 UTC, valfirst commented on vividus-extension-selenium/src/test/java/org/vividus/bdd/variable/ui/ContextProvidingDynamicVariableTests.java
> +    void shouldReturnZeroInCaseOfMissingContetx()
```suggestion
    void shouldReturnZeroInCaseOfMissingContext()
```

2021-10-04 21:18 UTC, valfirst requested changes

2021-10-04 21:18 UTC, valfirst commented on docs/modules/plugins/partials/dynamic-variables-ui.adoc
> +IMPORTANT: The variables rely on the contextual approach: it is necessary to switch contextto the target element.
new changes - new issues
```suggestion
IMPORTANT: The variables rely on the contextual approach: it is necessary to switch context to the target element.
```

2021-10-05 05:15 UTC, valfirst approved these changes

2021-10-05 06:39 UTC, abudevich approved these changes

2021-10-05 08:18 UTC, uarlouski approved these changes

2021-10-05 08:28 UTC, merged