[plugin-web-app] Bump default macOS version to 11.0
vividus-framework/vividus pull request #2053
Opened 2021-10-05 16:08 UTC by ikalinin1

fixes #1896

2021-10-05 17:14 UTC, valfirst requested changes

2021-10-05 17:14 UTC, valfirst commented on vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/safari/profile.properties
> +selenium.grid.platform-version=11.00
```suggestion
selenium.grid.platform-version=11.0
```

2021-10-06 07:47 UTC, ikalinin1 commented on vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/safari/profile.properties
> +selenium.grid.platform-version=11.00
Not working for saucelabs

2021-10-06 08:26 UTC, valfirst commented on vividus-plugin-web-app/src/main/resources/properties/profile/web/desktop/safari/profile.properties
> +selenium.grid.platform-version=11.00
that's ridiculous 🤦

2021-11-18 06:32 UTC, valfirst approved these changes

2021-11-18 11:02 UTC, merged