[plugin-web-app] Add ability to capture http response in proxy
vividus-framework/vividus pull request #2147
Opened 2021-11-04 12:29 UTC by uarlouski

2021-11-05 15:14 UTC, valfirst requested changes

2021-11-05 15:14 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +** `request data` - the request data includes the following keys:
```suggestion
* `$httpMessagePart` - the HTTP message part to save. One of:
** `URL` - The request URL.
** `URL query` - The request URL query parameters.
** `request data` - The request data includes the following keys:
```

2021-11-05 15:14 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +** `response data` - the response data includes the following keys:
```suggestion
** `response data` - The response data includes the following keys:
```

2021-11-05 15:14 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/proxy/model/HttpMessagePart.java
> +    private static Map<String, Object> extractFullRequestData(HarEntry harEntry)
it can be inlined

2021-11-05 16:05 UTC, valfirst requested changes

2021-11-05 16:05 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +** `URL` - The request URL
```suggestion
** `URL` - The request URL.
```

2021-11-05 16:05 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +** `URL query` - The request URL query parameters
```suggestion
** `URL query` - The request URL query parameters.
```

2021-11-05 16:08 UTC, uarlouski commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +** `URL` - The request URL
Friday evening :)

2021-11-05 16:29 UTC, valfirst approved these changes

2021-11-08 08:33 UTC, ikalinin1 approved these changes

2021-11-08 11:05 UTC, merged