[plugin-mobile-app] Add ability to switch to web view by name
vividus-framework/vividus pull request #2194
Opened 2021-11-15 09:02 UTC by uarlouski

2021-11-15 09:31 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/SetContextSteps.java
> +    @When("I switch to web view where name $comparisonRule `$value`")
```suggestion
    @When("I switch to web view with name which $comparisonRule `$value`")
```

2021-11-15 12:26 UTC, valfirst requested changes

2021-11-15 12:26 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/SetContextSteps.java
> +                            webViewMatcher, matchedWebViews.size()));
it's better to use `rule` here, instead of matcher, because matcher produces hardly readable message

2021-11-15 12:43 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/SetContextSteps.java
> +    @When("I switch to web view with name which $comparisonRule `$value`")
`which` vs `that`?

2021-11-15 13:56 UTC, ikalinin1 commented on docs/modules/plugins/pages/plugin-mobile-app.adoc
> +Switches context to a web view with name that matches the rule. See http://appium.io/docs/en/writing-running-appium/web/hybrid/[Automating hybrid apps] for more information.
pleaes reuse this 'See http://appium.io/docs/en/writing-running-appium/web/hybrid/[Automating hybrid apps] for more information.'

2021-11-15 13:59 UTC, ikalinin1 commented on vividus-plugin-mobile-app/src/main/java/org/vividus/bdd/mobileapp/steps/SetContextSteps.java
> +            if (webViewIndex >= 0 && webViewIndex < size)
I think makes sense to throw an exception in case of negative values, it might be out of the scope of this PR btw

2021-11-15 14:02 UTC, ikalinin1 approved these changes

2021-11-15 15:25 UTC, valfirst requested changes

2021-11-15 15:25 UTC, valfirst commented on vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
> +When I switch to web view with name which contains `vividustestapp`
```suggestion
When I switch to web view with name that contains `vividustestapp`
```

2021-11-15 15:25 UTC, valfirst commented on vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
> +Scenario: [Android] Verify steps: 'When I switch to native context', 'When I switch to web view with name which $comparisonRule `$value`'
```suggestion
Scenario: [Android] Verify steps: 'When I switch to native context', 'When I switch to web view with name that $comparisonRule `$value`'
```

2021-11-15 15:25 UTC, valfirst commented on vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
> +Scenario: [Android] Verify steps: 'When I switch to native context', 'When I switch to web view with name which $comparisonRule `$value`'
I think this fix in the test should go as a separate commit

2021-11-16 10:00 UTC, valfirst approved these changes

2021-11-16 10:01 UTC, merged