[plugin-mobile-app] Deprecate web view switching by index
vividus-framework/vividus pull request #2216
Opened 2021-11-18 13:47 UTC by uarlouski

The order of web views returned by appium is not reliable.
For android platform the web views are retrieved by parsing UNIX socket names from /proc/net/unix.
For ios platform the web views are consideres as separate processes within the active application.
Sorting the web view by Inode number for android or PID for ios doen't seem logical for end users and as practice shows the order is not guaranteed.

2021-11-18 13:51 UTC, valfirst requested changes

2021-11-18 13:51 UTC, valfirst commented on vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/steps/SetContextStepsTests.java
>      @ValueSource(ints = { 2, -2 })
Add
```
@SuppressWarnings("removal")
```

2021-11-18 13:51 UTC, valfirst commented on vividus-plugin-mobile-app/src/test/java/org/vividus/bdd/mobileapp/steps/SetContextStepsTests.java
>      @ValueSource(ints = { 2, -2 })
the same for the test above

2021-11-18 14:15 UTC, ikalinin1 approved these changes

2021-11-19 09:38 UTC, valfirst approved these changes

2021-11-19 09:40 UTC, merged