[docs] Adding the guide on database initialization from tests (#2273)
vividus-framework/vividus pull request #2286
Opened 2021-12-13 18:54 UTC by draker94

2021-12-13 19:40 UTC, valfirst requested changes

2021-12-13 19:40 UTC, valfirst commented on docs/modules/guides/pages/use-in-memory-db-to-manage-test-data.adoc
> +You could execute SQL on connection via the INIT property or through the step to execute SQL query.
```suggestion
DDL/DQL scripts could be run using either `INIT` property of the connection string or the step executing SQL queries.
```

2021-12-13 19:40 UTC, valfirst commented on docs/modules/guides/pages/use-in-memory-db-to-manage-test-data.adoc
> +Whichever method of initializing a table is chosen, you could use RUNSCRIPT commands with the path to SQL files. Here you can specify absolute path to file or use the 'classpath:/' prefix - files wil
```suggestion
Whichever method of tables initialization is chosen, `RUNSCRIPT` statement with the path to SQL files could be used. Here you can specify absolute path to file or use the 'classpath:/' prefix - files will be searched from 'src/main/resources' folder relatively.
```

2021-12-13 19:40 UTC, valfirst commented on docs/modules/guides/pages/use-in-memory-db-to-manage-test-data.adoc
> +.. Using INIT property
```suggestion
.. Using `INIT` property
```

2021-12-13 19:40 UTC, valfirst commented on docs/modules/guides/pages/use-in-memory-db-to-manage-test-data.adoc
> + - using INIT property data loaded into the database once and can no longer be change.
```suggestion
 - using `INIT` property data loaded into the database once and can no longer be change.
```

2021-12-13 19:40 UTC, valfirst commented on docs/modules/guides/pages/use-in-memory-db-to-manage-test-data.adoc
> + - if you use table initialization in the step, you only need to specify connection parameters in the properties file and initialize the table in the test.
```suggestion
 - if you use tables initialization in the step, you only need to specify the connection parameters in the properties file and execute DDL script in the test.
```

2021-12-13 19:40 UTC, valfirst commented on docs/modules/guides/pages/use-in-memory-db-to-manage-test-data.adoc
> +WARNING: If you are using table initialization in the step, do not forget to set the property http://www.h2database.com/html/features.html#in_memory_databases[DB_CLOSE_DELAY].
```suggestion
WARNING: If you are using table initialization in the step, do not forget to set the property http://www.h2database.com/html/features.html#in_memory_databases[`DB_CLOSE_DELAY`].
```

2021-12-13 19:40 UTC, valfirst commented on docs/modules/guides/pages/use-in-memory-db-to-manage-test-data.adoc
> +.Initialization database
```suggestion
.Initialization of the database
```

2021-12-13 19:40 UTC, valfirst commented on docs/modules/guides/pages/use-in-memory-db-to-manage-test-data.adoc
> +.Initialization database with RUNSCRIPT
```suggestion
.Initialization of database with `RUNSCRIPT`
```

2021-12-13 19:40 UTC, valfirst commented on docs/modules/guides/pages/use-in-memory-db-to-manage-test-data.adoc
> +. Use the configured connection and the initialized database to execute SQL
```suggestion
----

. Use the configured connection and the initialized database to execute SQL
```

2021-12-13 19:40 UTC, valfirst commented on docs/modules/guides/pages/use-in-memory-db-to-manage-test-data.adoc
> +.Execute SQL against H2 database if the table was created in the step with the schema 'test'
```suggestion
.Execute DML script against H2 database initialized in the step with the schema `test`
```

2021-12-13 19:40 UTC, valfirst commented on docs/modules/guides/pages/use-in-memory-db-to-manage-test-data.adoc
> +SELECT * FROM test.students
it makes sense to put `INSERT`, `UPDATE` or any other DML statement

2021-12-13 19:40 UTC, valfirst commented on vividus-tests/src/main/resources/properties/suite/integration/suite.properties
> +db.connection.testh2db1.password=
```suggestion
db.connection.testh2db-modifiable.driver-class-name=org.h2.Driver
db.connection.testh2db-modifiable.url=jdbc:h2:mem:test;\
  DB_CLOSE_DELAY=-1;\
  DATABASE_TO_UPPER=FALSE;
db.connection.testh2db-modifiable.username=
db.connection.testh2db-modifiable.password=
```

2021-12-13 19:40 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/Databases.story
> +CREATE TABLE if not exists test.launch_rockets (name VARCHAR(50) NOT NULL, 	payload_cost VARCHAR(100) NOT NULL, country VARCHAR(100) NOT NULL);
```suggestion
CREATE TABLE if not exists test.launch_rockets (name VARCHAR(50) NOT NULL, payload_cost VARCHAR(100) NOT NULL, country VARCHAR(100) NOT NULL);
```

2021-12-14 10:28 UTC, ikalinin1 approved these changes

2021-12-14 14:16 UTC, valfirst approved these changes

2021-12-14 14:20 UTC, merged