[extension-selenium] Update screenshot taking step (#1795)
vividus-framework/vividus pull request #2295
Opened 2021-12-16 15:04 UTC by draker94

Update screenshot taking step (`When I take screenshot`) to publish screenshot only in Allure Report.

2021-12-16 20:32 UTC, valfirst requested changes

2021-12-16 20:32 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +=== Take a screenshot in Allure Report
```suggestion
=== Take a screenshot
```
we may use different reporting engines, so UI steps should not declare any explicit reporting engine

2021-12-16 20:32 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +Takes a screenshot and publish it to the allure report.
```suggestion
Takes a screenshot and publish it to the report.
```

2021-12-16 20:32 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +TIP: In the report screenshot will be posted with additional information like date and browser.
```suggestion
```
these are implementation details, no need to put it to the docs

2021-12-16 20:32 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/AbstractScreenshotTaker.java
> +        LOGGER.atInfo().addArgument(screenshotPublishedName).log(SCREENSHOT_TAKEN_LOG_MESSAGE);
```suggestion
```
redundant, this info will be in report any way

2021-12-16 20:32 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/ScreenshotTaker.java
> +    void takeScreenshotInAllure(String screenshotName);
why is new method needed? why can't we use `Optional<Screenshot> takeScreenshot(String screenshotName);`?

2021-12-16 20:32 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/AbstractScreenshotTaker.java
> +        Attachment attachment = new Attachment(takeScreenshotAsByteArray(), screenshotPublishedName);
it makes sense to provide content type as well

2021-12-17 15:28 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/steps/ui/ScreenshotTakingSteps.java
> +    public void whenITakeScreenshot()
```suggestion
    public void takeScreenshot()
```
I know it's a bit out of scope, but it's a good chance to change this ugly name

2021-12-17 15:37 UTC, valfirst requested changes

2021-12-17 15:37 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/AbstractScreenshotTaker.java
> +    }
what's the reason to add a default implementation? Web and Mobile App screenshot takers have this method implemented, but in different ways

2021-12-17 15:37 UTC, valfirst commented on vividus-extension-selenium/src/main/resources/spring.xml
> -                <constructor-arg value="${ui.screenshot.directory}" />
it makes sense to remove the default property as well: https://github.com/vividus-framework/vividus/blob/b329f3c1ffdd5d71e40f3f70800f76d08a789d6e/vividus-extension-selenium/src/main/resources/properties/defaults/default.properties#L25

2021-12-20 08:08 UTC, valfirst approved these changes

2021-12-20 08:12 UTC, ikalinin1 approved these changes

2021-12-20 08:30 UTC, uarlouski approved these changes

2021-12-20 08:58 UTC, merged