Rp
vividus-framework/vividus pull request #2300
Opened 2021-12-17 14:52 UTC by ikalinin1

2021-12-17 15:21 UTC, valfirst requested changes

2021-12-17 15:21 UTC, valfirst commented on vividus-agent-reportportal/src/main/java/org/vividus/reportportal/jbehave/AdaptedDelegatingReportPortalStoryReporter.java
> +                rq.setLogTime(Calendar.getInstance().getTime());
```suggestion
                rq.setLogTime(new Date());
```
?

2021-12-17 15:21 UTC, valfirst commented on vividus-agent-reportportal/src/main/resources/properties/defaults/default.properties
>  bdd.generate-view-after-batches=#{T(String).valueOf(${system.rp.enable} || (T(System).getProperty('rp.enable')?:false))}
is it needed?

2021-12-20 12:50 UTC, valfirst requested changes

2021-12-20 12:50 UTC, valfirst commented on vividus-agent-reportportal/build.gradle
> +    implementation(group: 'com.epam.reportportal', name: 'logger-java-log4j', version: '5.1.1')
```suggestion
    implementation(group: 'com.epam.reportportal', name: 'logger-java-log4j', version: '5.1.2')
```

2021-12-20 15:17 UTC, valfirst commented on vividus-agent-reportportal/src/main/java/org/vividus/reportportal/jbehave/AdaptedDelegatingReportPortalStoryReporter.java
> +import java.util.Calendar;
```suggestion
```

2021-12-20 15:32 UTC, valfirst commented on vividus-agent-reportportal/build.gradle
> +    implementation(group: 'com.epam.reportportal', name: 'logger-java-log4j', version: '5.1.2')
```suggestion
    implementation(group: 'com.epam.reportportal', name: 'logger-java-log4j', version: '5.1.3')
```
welcome to log4jhell

2021-12-21 08:18 UTC, valfirst approved these changes

2021-12-21 08:57 UTC, uarlouski commented on vividus-agent-reportportal/src/main/java/org/vividus/reportportal/jbehave/AdaptedDelegatingReportPortalStoryReporter.java
> +    public void onAssertionFailure(@SuppressWarnings("unused") AssertionFailedEvent event)
used at 97

2021-12-21 11:04 UTC, valfirst approved these changes

2021-12-21 11:29 UTC, uarlouski approved these changes

2021-12-21 11:54 UTC, merged