[WIP] [visual-testing] Add possibility to disable screenshots downscale
vividus-framework/vividus pull request #2323
Opened 2021-12-24 13:46 UTC by EDbarvinsky

Fixes #2195

2021-12-24 13:51 UTC, EDbarvinsky commented
There is several things about this PR.
The first one is that for web application visual check  if dpr != 1 then it is not working correctly and current wrapping for cords provider does not fix that.
So there is a question should be documents be updated for web module?

Another one will we set up integration tests execution for mobile devices in case if we use original image instead ?

2021-12-28 08:55 UTC, EDbarvinsky commented
Issue for web app is added https://github.com/vividus-framework/vividus/issues/2334

2021-12-28 09:20 UTC, EDbarvinsky commented on vividus-plugin-mobile-app/src/main/resources/spring.xml
> +    <bean id ="ashotFactory" class="org.vividus.selenium.mobileapp.screenshot.MobileAppAshotFactory" parent="abstractAshotFactory">
to remove

2021-12-28 09:24 UTC, valfirst requested changes

2021-12-28 09:24 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/AbstractAshotFactory.java
> +    public abstract double getDpr();
why is this change needed?

2021-12-28 09:24 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/screenshot/DprAwareCoordsProvider.java
> +        int dpr = downscale ? 1 : (int) super.getMobileAppWebDriverManager().getDpr();
is `dpr` always integer?

2021-12-28 09:24 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/screenshot/MobileAppAshotFactory.java
> +            : mobileAppWebDriverManager.getStatusBarSize() * (int) getDpr();
```suggestion
        int statusBarSize = mobileAppWebDriverManager.getStatusBarSize()
        if (downscale)
        {
            statusBarSize = statusBarSize * (int) getDpr();
        }
```

2021-12-28 09:24 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/resources/spring.xml
> +    <bean id="mobileAppWebDriverManager" class="org.vividus.selenium.mobileapp.MobileAppWebDriverManager" parent="genericWebDriverManager" />
noisy change

2021-12-28 09:27 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/resources/spring.xml
> +    <bean id="coordsProvider" class="org.vividus.selenium.mobileapp.screenshot.DprAwareCoordsProvider">
it seems `NativeHeaderAwareCoordsProvider` is not going to be used explicitly, so `DprAwareCoordsProvider` and `NativeHeaderAwareCoordsProvider` can be merged into a new `MobileAppCoordsProvider`

2022-01-05 09:31 UTC, valfirst requested changes

2022-01-05 09:31 UTC, valfirst commented on docs/modules/plugins/pages/plugin-visual.adoc
> +image::origininal_and_downscaled_checkpoints.png[Difference between original and dpr downscaled image]
add more details around the image: what is the original image, what is the downscaled image, what is DPR (please bear in mind it's not obvious for users)

2022-01-05 09:31 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/screenshot/MobileAppCoordsProvider.java
> +        coords.height = CoordsUtil.multiply(coords.height, dpr);
```suggestion
        return CoordsUtil.scale(coords, dpr);
```

2022-01-05 09:31 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/screenshot/util/CoordsUtil.java
> +    public static int multiply(int value, double dpr)
```suggestion
    public static int scale(int value, double dpr)
```

2022-01-05 09:31 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/screenshot/MobileAppCoordsProvider.java
> +    public MobileAppWebDriverManager getMobileAppWebDriverManager()
is it used?

2022-01-05 11:40 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/screenshot/util/CoordsUtil.java
> +        coords.height = CoordsUtil.scale(coords.height, dpr);
do not change the input, create a new object `Coords`

2022-01-05 11:40 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/screenshot/util/CoordsUtil.java
> +        coords.x = CoordsUtil.scale(coords.x, dpr);
Fully-qualified name is not needed:
`CoordsUtil.scale` -> `scale`

2022-01-05 12:16 UTC, EDbarvinsky commented
[Last run](https://github.com/vividus-framework/vividus/runs/4711876825?check_suite_focus=true) related to changes in CI config

2022-01-05 12:18 UTC, valfirst approved these changes

2022-01-05 13:56 UTC, merged