[plugin-mobile-app] Handle the exception if status bar height from se…
vividus-framework/vividus pull request #2346
Opened 2022-01-03 11:45 UTC by EDbarvinsky

…ssion details is null

Received exception in [CI example](https://github.com/vividus-framework/vividus/runs/4689829224?check_suite_focus=true#step:21:2124)

2022-01-03 13:23 UTC, valfirst requested changes

2022-01-03 13:23 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManager.java
>      }
```suggestion
    private int getStatBarHeightSafely()
    {
        Long statBarHeight = getStatBarHeightUnsafely();
        if (statBarHeight == null)
        {
            throw new IllegalArgumentException("Unable to receive status bar height. Received value is null.");
        }
        return statBarHeight.intValue();
    }
    
    private Long getStatBarHeightUnsafely()
    {
        return (Long) getSessionDetail("statBarHeight");
    }
```

2022-01-03 13:23 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManager.java
>                  // org.openqa.selenium.WebDriverException:
```java
            Long statBarHeight;
            try
            {
                statBarHeight = getStatBarHeightUnsafely();
            }
            catch (WebDriverException)
            {
                statBarHeight = null;
            }
            // Handling SauceLabs error:
            ...
```

2022-01-03 14:45 UTC, valfirst requested changes

2022-01-03 14:45 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManager.java
> +            return statBarHeight.intValue();
```java
Number statBarHeight;
try
{
    statBarHeight = getStatBarHeightUnsafely();
}
catch (WebDriverException e)
{
    // Handling SauceLabs error:
    // org.openqa.selenium.WebDriverException:
    // failed serving request GET https://production-sushiboat.default/wd/hub/session/XXXX
    statBarHeight = null;
}
if (null == statBarHeight)
{
    // Appium 1.21.0 or higher is required
    Map<String, ?> deviceScreenInfo = javascriptActions.executeScript("mobile:deviceScreenInfo");
    Map<String, ?> statusBarSize = (Map<String, ?>) deviceScreenInfo.get("statusBarSize");
    statBarHeight = (Number) statusBarSize.get(HEIGHT));
}
return statBarHeight.intValue();
```

2022-01-03 15:18 UTC, valfirst approved these changes

2022-01-03 16:19 UTC, uarlouski commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManager.java
> +        if (statBarHeight == null)
we usually use Validate.isTrue from apache commons lang3 lib

2022-01-03 16:22 UTC, uarlouski approved these changes

2022-01-04 07:12 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManager.java
> +            throw new IllegalArgumentException("Unable to receive status bar height. Received value is null.");
```suggestion
            throw new IllegalStateException("Unable to receive status bar height. Received value is null.");
```

2022-01-04 07:22 UTC, valfirst commented on vividus-plugin-mobile-app/src/test/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManagerTests.java
> +        Exception exception = assertThrows(IllegalArgumentException.class, driverManager::getStatusBarSize);
```suggestion
        var exception = assertThrows(IllegalStateException.class, driverManager::getStatusBarSize);
```

2022-01-04 08:05 UTC, valfirst commented on vividus-plugin-mobile-app/src/test/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManagerTests.java
> +        assertEquals("Unable to receive status bar height. Received value is null.", exception.getMessage());
```suggestion
        assertEquals("Unable to receive status bar height. Received value is null", exception.getMessage());
```

2022-01-04 08:48 UTC, merged