[vividus-plugin-web-app] Add ability to work with invisible elements in nested steps
vividus-framework/vividus pull request #2563
Opened 2022-03-10 13:54 UTC by draker94

2022-03-10 14:15 UTC, valfirst requested changes

2022-03-10 14:15 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +Executes the steps against all elements found by locator.
we need to define explicitly, that the current iteration element is set as a search context, and describe how context is managed by the step

2022-03-10 14:15 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/GenericNestedSteps.story
> +Description: Integration tests for GenericNestedSteps class.
```suggestion
```

2022-03-10 14:15 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/NestedSteps.story
> +Given I am on a page with the URL 'https://demo.guru99.com/'
we're changing our tests to do not depend on external resources, if our test site doesn't have needed functionality, please feel free to open a PR

2022-03-11 06:08 UTC, valfirst approved these changes

2022-03-11 06:35 UTC, ikalinin1 commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +=== Perform steps for all elements
It's more like for-each not for all?

2022-03-11 11:04 UTC, uarlouski approved these changes

2022-03-14 11:16 UTC, ikalinin1 approved these changes

2022-03-17 11:38 UTC, merged