[extension-selenium] Add possibility to set context without resetting…
vividus-framework/vividus pull request #2566
Opened 2022-03-12 11:40 UTC by ikalinin1

… current one

2022-03-12 12:57 UTC, valfirst requested changes

2022-03-12 12:57 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +When I change context to element located `$locator` using current context
```suggestion
When I change context to element located `$locator` in scope of current context
```
?

2022-03-12 12:57 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/SetContextStepsTests.story
> +
it makes sense to add some validation here

2022-03-15 16:50 UTC, uarlouski approved these changes

2022-03-16 09:11 UTC, valfirst requested changes

2022-03-16 09:11 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/steps/ui/GenericSetContextSteps.java
>          WebElement element = getBaseValidations().assertIfElementExists("Element to set context", locator);
we should avoid using deprecated methods in new steps

2022-03-18 10:47 UTC, valfirst approved these changes

2022-03-21 09:31 UTC, uarlouski approved these changes

2022-03-21 10:57 UTC, merged