[plugin-json] Allow to save JSON as variable
vividus-framework/vividus pull request #2567
Opened 2022-03-12 12:00 UTC by ikalinin1

The docs and unit tests are missing because I want to discuss a few things:

1. Wording
2. Approach: use context and JSON string, or use only JSON string as an input parameter

2022-03-12 13:00 UTC, valfirst commented
> 1.  Wording

I proposed the wording in the comment
\
\
> 2. Approach: use context and JSON string, or use only JSON string as an input parameter

We need to support both context and JSON input string (2 steps are needed)

2022-03-14 07:36 UTC, valfirst requested changes

2022-03-17 13:41 UTC, valfirst approved these changes

2022-03-18 08:04 UTC, uarlouski commented on vividus-plugin-json/src/main/java/org/vividus/json/steps/JsonSteps.java
> +        variableContext.putVariable(scopes, variableName, jsonUtils.toObject(getActualJson(), Object.class));
why not to
convertJsonToVariable(getActualJson(), scopes, var)

2022-03-18 08:04 UTC, uarlouski approved these changes

2022-03-18 08:27 UTC, uarlouski approved these changes

2022-03-18 08:40 UTC, abudevich approved these changes

2022-03-18 12:06 UTC, merged