[vividus-plugin-rest-api] Add possibility to validate response archive with comparison rule
vividus-framework/vividus pull request #2711
Opened 2022-04-29 08:29 UTC by draker94

Relates #2545

2022-04-29 10:57 UTC, valfirst requested changes

2022-04-29 10:57 UTC, valfirst commented on docs/modules/plugins/pages/plugin-rest-api.adoc
> +If column with comparison rule is not exists, verifies that one of archive entries has one of the specified names.
```suggestion
If comparison rule column does not exists, the verification that archive entries have the specified names is performed.
```

2022-04-29 10:57 UTC, valfirst commented on vividus-plugin-rest-api/src/main/java/org/vividus/steps/api/HttpResponseValidationSteps.java
> +                        "The response archive contains entry matches the comparison rule '%s' with name pattern '%s'",
```suggestion
                        "The response archive contains entry matching the comparison rule '%s' with name pattern '%s'",
```

2022-05-02 14:29 UTC, valfirst approved these changes

2022-05-04 07:31 UTC, uarlouski approved these changes

2022-05-04 09:08 UTC, ikalinin1 commented on docs/modules/plugins/pages/plugin-rest-api.adoc
>  ----
```
Then the response archive contains entries with the names:$parameters
```

Refactor wording to:
```
Then response archive contains entries with names:$parameters
```

2022-05-04 10:11 UTC, ikalinin1 approved these changes

2022-05-05 07:59 UTC, merged