[plugin-mobile-app] Add step to clear a field and keep keyboard open
vividus-framework/vividus pull request #2717
Opened 2022-04-29 15:53 UTC by VerkhovtsovPavel

Closes https://github.com/vividus-framework/vividus/issues/2617

2022-05-02 13:51 UTC, valfirst requested changes

2022-05-02 13:51 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/KeyboardActions.java
> +    public void clearTextAndHide(WebElement element)
it makes sense to have 2 methods in `KeyboardActions`:
- `clearText`
- `hideKeyboard`

any combinations of these methods invocations should be done in steps

2022-05-02 13:51 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/steps/KeyboardSteps.java
> +     * Clear a field located by the <b>locator</b>
need to document explicitly that this step closes keyboard

2022-05-07 19:00 UTC, valfirst reviewed
-

2022-05-07 19:06 UTC, valfirst approved these changes

2022-05-10 07:24 UTC, ikalinin1 approved these changes

2022-05-10 07:37 UTC, uarlouski commented on vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/steps/KeyboardSteps.java
> +    @When("I clear field located `$locator` and keep keyboard opened")
hm I think it should be "open" => https://english.stackexchange.com/questions/141547/opened-vs-open

2022-05-13 14:42 UTC, ikalinin1 commented on docs/modules/plugins/pages/plugin-mobile-app.adoc
> +When I clear field located `accessibilityId(username)` and keep keyboard opened
```suggestion
When I clear field located `accessibilityId(username)` and keep keyboard open
```

2022-05-13 14:44 UTC, ikalinin1 commented on vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
> +
```suggestion
Scenario: Verify step: 'When I clear field located `$locator` and keep keyboard open'
Meta:
    @requirementId 2617
    @targetPlatform ios
!-- Typing on android emulator doesn't shows a keyboard.
When I clear field located `accessibilityId(nameInput)` and keep keyboard open
Then number of elements found by `xpath(<nameDisplayXpath>)` is equal to `1`
Then number of elements found by `<keyboardLocator>` is equal to `1`
When I tap on element located `accessibilityId(Return)`
Then number of elements found by `<keyboardLocator>` is equal to `0`


```

2022-05-13 14:44 UTC, ikalinin1 commented on docs/modules/plugins/pages/plugin-mobile-app.adoc
> +=== Clear field and keep keyboard opened
```suggestion
=== Clear field and keep keyboard open
```

2022-05-13 15:18 UTC, valfirst commented on docs/modules/plugins/pages/plugin-mobile-app.adoc
> +.Clear text and keep keyboard opened
```suggestion
.Clear text and keep keyboard open
```

2022-05-13 15:21 UTC, uarlouski approved these changes

2022-05-13 22:09 UTC, merged