[extnesion-selenium] Enable normalization and quotes escaping for reu…
vividus-framework/vividus pull request #2764
Opened 2022-05-16 19:04 UTC by ikalinin1

…sable locator

2022-05-17 08:12 UTC, valfirst requested changes

2022-05-17 08:12 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/ui/util/LocatorConversionUtils.java
> +        var pattern = locatorPattern.getPattern();
we don't use `var` in production code (yet)

2022-05-17 08:12 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/ui/util/LocatorUtil.java
> +package org.vividus.ui.util;
since it's moved: `LocatorUtil` -> `XpathLocatorUtils`

2022-05-17 15:56 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/ui/web/util/WebXpathLocatorUtil.java
> +public final class WebXpathLocatorUtil
```suggestion
public final class WebXpathLocatorUtils
```

2022-05-18 07:53 UTC, uarlouski approved these changes

2022-05-18 08:23 UTC, merged