[plugin-web-app] Introduce step allowing to execute JS and save resul…
vividus-framework/vividus pull request #2794
Opened 2022-05-23 14:14 UTC by ikalinin1

…t into variable

2022-05-23 14:56 UTC, valfirst requested changes

2022-05-23 14:56 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetVariableSteps.java
> +     * Performs passed JavaScript code on the opened page
```suggestion
     * Executes passed JavaScript code on the opened page
```

2022-05-23 14:56 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetVariableSteps.java
> +    @When("I execute javascript `$jsCode` and save result to `$scopes` variable `$variableName`")
it makes sense to update the step executing async JS as well

2022-05-24 08:41 UTC, uarlouski approved these changes

2022-05-24 09:14 UTC, valfirst requested changes

2022-05-24 11:18 UTC, valfirst approved these changes

2022-05-24 19:53 UTC, merged