[plugin-visual] Allow to overwrite default DiffMarkUpPolicy
vividus-framework/vividus pull request #2823
Opened 2022-05-31 13:12 UTC by ikalinin1

2022-05-31 13:41 UTC, valfirst requested changes

2022-06-01 12:49 UTC, valfirst requested changes

2022-06-01 12:49 UTC, valfirst commented on vividus-plugin-visual/src/main/java/org/vividus/visual/engine/VisualTestingEngine.java
> +    private ImageDiff findImageDiff(Screenshot expected, Screenshot actual, int height, int width,
this method can be inlined now

2022-06-01 13:20 UTC, uarlouski commented on vividus-plugin-visual/src/main/java/org/vividus/visual/engine/DiffMarkUpPolicyFactory.java
> +public class DiffMarkUpPolicyFactory
is it "mark up" or "markup"?

2022-06-01 16:00 UTC, valfirst commented on vividus-plugin-visual/src/main/java/org/vividus/visual/engine/VisualTestingEngine.java
> +    private final DiffMarkupPolicyFactory diffMarkUpPolicyFactory;
```suggestion
    private final DiffMarkupPolicyFactory diffMarkupPolicyFactory;
```
please fix all such references

2022-06-01 21:15 UTC, valfirst approved these changes

2022-06-01 21:15 UTC, merged