[plugin-visual] Add possibility to override baseline repository
vividus-framework/vividus pull request #2859
Opened 2022-06-10 13:58 UTC by ikalinin1

2022-06-10 14:22 UTC, valfirst requested changes

2022-06-10 14:22 UTC, valfirst commented on docs/modules/plugins/pages/plugin-visual.adoc
> +* `repository` - The name of repository.
we need to indicate that only `filesystem` is available out of the box

2022-06-10 14:22 UTC, valfirst commented on docs/modules/plugins/pages/plugin-visual.adoc
> +* `repository` - The name of repository.
here and in similar parameters descriptions

2022-06-10 14:22 UTC, valfirst commented on vividus-plugin-visual/src/main/java/org/vividus/visual/engine/BaselineRepositoryFactory.java
> +public interface BaselineRepositoryFactory
why is it needed?
why not to inject just `Map<String, BaselineRepository> baselineRepositories`

2022-06-13 09:03 UTC, uarlouski commented on docs/modules/plugins/pages/plugin-visual.adoc
> +* `actionType` - {visual-testing-actions}.
can you please align formats of param names by prepending them with $?

2022-06-13 10:41 UTC, uarlouski approved these changes

2022-06-13 10:48 UTC, valfirst approved these changes

2022-06-13 11:05 UTC, valfirst requested changes
System tests are failed

2022-06-13 11:45 UTC, valfirst approved these changes

2022-06-13 15:05 UTC, valfirst approved these changes

2022-06-13 17:43 UTC, merged