[plugin-visual] Rename baseline repository to baseline storage
vividus-framework/vividus pull request #2894
Opened 2022-06-21 13:20 UTC by ikalinin1

2022-06-21 15:03 UTC, valfirst requested changes

2022-06-21 15:03 UTC, valfirst commented on docs/modules/plugins/pages/plugin-visual.adoc
> +|Allows to override default xref:developer-guides:plugins.adoc#_baseline_storagess[baseline storage].
```suggestion
|Allows to override default xref:developer-guides:plugins.adoc#_baseline_storages[baseline storage].
```

2022-06-21 15:03 UTC, valfirst commented on vividus-plugin-visual/src/main/java/org/vividus/visual/VisualSteps.java
> +            Optional<String> baselinestorage, Optional<ScreenshotConfiguration> screenshotConfiguration)
```suggestion
            Optional<String> baselineStorage, Optional<ScreenshotConfiguration> screenshotConfiguration)
```

2022-06-22 08:45 UTC, valfirst approved these changes

2022-06-22 09:15 UTC, uarlouski approved these changes

2022-06-22 11:04 UTC, merged