[plugin-mobile-app] Fix invalid dpr calculation for android
vividus-framework/vividus pull request #2914
Opened 2022-06-29 15:02 UTC by uarlouski

2022-07-01 07:37 UTC, uarlouski commented
> deviceScreenSize - is it always presented? Maybe handle corner cases?

it for sure exists for 4 years in both appium uiautomator2 and espresso drivers, if you have any thought about where corner cases may occur please share

2022-07-01 11:14 UTC, ikalinin1 commented
> > deviceScreenSize - is it always presented? Maybe handle corner cases?
> 
> it for sure exists for 4 years in both appium uiautomator2 and espresso drivers, if you have any thought about where corner cases may occur please share

What about android tv? 
What about the real device?
Corner case is the case if the session doesn't have deviceScreenSize

2022-07-06 08:50 UTC, valfirst requested changes

2022-07-12 07:15 UTC, ikalinin1 commented on vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManager.java
> +    private float calculateDpr(float screenHeight)
Per discussion please update to use pixelRatio when available

2022-09-06 09:42 UTC, ikalinin1 approved these changes

2022-09-07 10:58 UTC, valfirst approved these changes

2022-09-07 10:59 UTC, merged