Add Appium Setup Guide
vividus-framework/vividus pull request #2925
Opened 2022-07-05 06:43 UTC by Aliaksei-Andreyeu

Adds a document into the user-guides section that describes installation and setup processes for Appium.
Also contains the WebDriverAgent setup section and a F.A.Q.

2022-07-06 10:47 UTC, valfirst commented
Please move images from `ROOT` to `user-guides`

2022-07-06 11:03 UTC, valfirst requested changes

2022-07-06 11:03 UTC, valfirst commented on docs/modules/user-guides/pages/appium-setup.adoc
> +.Click to expand the section
```suggestion
.Click to see details
```

2022-07-06 11:03 UTC, valfirst commented on docs/modules/user-guides/pages/appium-setup.adoc
> +.Click to expand the section
```suggestion
.Click to see details
```

2022-07-06 11:03 UTC, valfirst commented on docs/modules/user-guides/pages/appium-setup.adoc
> +.Click to expand the section
```suggestion
.Click to see details
```

2022-07-06 11:03 UTC, valfirst commented on docs/modules/user-guides/pages/appium-setup.adoc
> +You are ready to run tests! Just add properties from above to your .properties file and use xref:appium-setup.adoc#_running_tests_on_simulators[the same approach as for Simulators]
```suggestion
You are ready to run tests! Just add properties from above to your `*.properties` file and use xref:appium-setup.adoc#_running_tests_on_simulators[the same approach as for Simulators]
```

2022-07-07 08:14 UTC, valfirst requested changes

2022-07-07 08:14 UTC, valfirst commented on docs/modules/user-guides/pages/appium-setup.adoc
> +Before running vividus scenarios it is necessary to pass Desired Capabilities to Appium Server. Use them as properties with `selenium.grid.capabilities.` prefix. Then just put these capabilities into
```suggestion
Before running VIVIDUS scenarios it is necessary to pass Desired Capabilities to Appium Server. Use them as properties with `selenium.grid.capabilities.` prefix. Then just put these capabilities into the appropriate `*.properties` file. Please see examples below:
```

2022-07-08 07:23 UTC, valfirst approved these changes

2022-07-11 08:05 UTC, uarlouski commented on docs/modules/user-guides/pages/appium-setup.adoc
> +----
Imho it's better to put each set of props into separate  source section e.g.
.Example of iOS properties
[source, property]
----
......
----

.Example of Android properties
[source, property]
----
......
----

2022-07-11 08:07 UTC, uarlouski commented on docs/modules/user-guides/pages/appium-setup.adoc
> +====
https://github.com/vividus-framework/vividus/pull/2925/files#r917651417 same here, so end users can copy the content into clipboard without the need to remote unnecessary stuff

2022-07-11 08:12 UTC, ikalinin1 commented on docs/modules/user-guides/pages/appium-setup.adoc
> +== Basic setup
```suggestion
== Environment setup
```

```suggestion
== Mobile developer tools setup
```

2022-07-11 08:13 UTC, ikalinin1 commented on docs/modules/user-guides/pages/appium-setup.adoc
> +== Running tests on Simulators
```suggestion
== Running tests on Simulators/Emulators
```

2022-07-11 08:14 UTC, ikalinin1 approved these changes

2022-07-11 10:13 UTC, merged