[docs] Add documentation for executable steps
vividus-framework/vividus pull request #2942
Opened 2022-07-12 14:11 UTC by draker94

2022-07-12 16:05 UTC, valfirst requested changes

2022-07-12 16:05 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +* `$condition` - The verifiable condition.
Please add the description how is result of the condition checked: true vs anything to else

2022-07-12 16:05 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +* `$stepsToExecute` - The ExamplesTable with a single column containing the steps to execute if condition is true.
it makes sense to define the name of the single column

2022-07-12 16:05 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +=== Execute steps when a variable is not set
```suggestion
=== Execute steps if a variable is not set
```

2022-07-12 16:05 UTC, valfirst commented on docs/modules/commons/pages/vividus-steps.adoc
> +Execute steps if the variable with `$name` is not set into context.
Please see the above comment about step intro and parameters

2022-07-13 09:59 UTC, ikalinin1 commented on docs/modules/commons/pages/vividus-steps.adoc
> +=== Execute steps N times
Please add an example of usage nested step inside nested steps

2022-07-13 10:00 UTC, ikalinin1 commented on docs/modules/commons/pages/vividus-steps.adoc
> +=== Execute steps N times
For all the steps

2022-07-13 10:13 UTC, uarlouski approved these changes

2022-07-13 11:10 UTC, valfirst approved these changes

2022-07-13 11:27 UTC, ikalinin1 approved these changes

2022-07-13 11:35 UTC, merged