Document batch level variables
vividus-framework/vividus pull request #3048
Opened 2022-08-10 16:49 UTC by Nastiachka

2022-08-11 06:46 UTC, valfirst requested changes

2022-08-11 06:46 UTC, valfirst commented on docs/modules/commons/pages/variables.adoc
> +a|Such variables are declared only via suite properties with bdd.variables.batch-<batch-number>. prefix and available throughout the execution of the batch in the suite. An attempt to create the batc
```suggestion
a|Such variables are declared only with `bdd.variables.batch-<batch-number>.` prefix and available throughout the execution of the batch in the suite. An attempt to create the batch-scoped variables during test execution leads to an error.
```

2022-08-11 18:15 UTC, uarlouski approved these changes

2022-08-12 07:12 UTC, ikalinin1 approved these changes

2022-08-12 07:22 UTC, uarlouski approved these changes

2022-08-12 08:22 UTC, merged