Delete file from device
vividus-framework/vividus pull request #3083
Opened 2022-08-19 08:59 UTC by IBrun

2022-08-19 12:01 UTC, valfirst requested changes

2022-08-19 12:01 UTC, valfirst commented on vividus-tests/src/main/resources/story/system/mobile_app/MobileAppStepsTests.story
> +When I delete file `/Media/DCIM/100APPLE/IMG_0001.JPG` from device
add a comment that validation is not possible for this scenario yet

2022-08-22 07:50 UTC, ikalinin1 approved these changes

2022-08-22 07:53 UTC, valfirst requested changes

2022-08-22 07:53 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/steps/DeviceSteps.java
> +     */
javadocs should be almost equal to the documentation

2022-08-24 08:00 UTC, valfirst approved these changes

2022-08-24 09:58 UTC, uarlouski approved these changes

2022-08-24 10:49 UTC, merged