Wait for message
vividus-framework/vividus pull request #3097
Opened 2022-08-24 12:12 UTC by ikalinin1

2022-08-24 15:35 UTC, valfirst requested changes

2022-08-24 20:14 UTC, ikalinin1 commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/JsValidationSteps.java
> +                    JsValidationSteps.toString(logEntries), regex);
<img width="395" alt="image" src="https://user-images.githubusercontent.com/17816729/186514291-e9c2db77-0753-4ffb-923c-393ae7938a60.png">

<img width="909" alt="image" src="https://user-images.githubusercontent.com/17816729/186514451-68d32237-c9fb-43e6-a32f-f52363bfbad4.png">

2022-08-25 07:15 UTC, valfirst approved these changes

2022-08-25 07:28 UTC, uarlouski approved these changes

2022-08-25 07:31 UTC, merged