[docs] Update docker guide for Selenium 4
vividus-framework/vividus pull request #3223
Opened 2022-10-03 15:44 UTC by uarlouski

Closes #3049

2022-10-03 16:05 UTC, ikalinin1 commented on docs/modules/user-guides/pages/pipeline-with-proxy.adoc
> +                withDockerContainer(image: 'adoptopenjdk/openjdk16', args: "--net ${vividusNetwork} --name ${vividusProxyHost}") {<1> <4>
17 ?

2022-10-03 16:06 UTC, ikalinin1 commented on docs/modules/user-guides/pages/pipeline-with-proxy.adoc
> +                        configuration.profiles=web/headless/chrome
Refactor to use web/docker

2022-10-03 21:43 UTC, valfirst requested changes

2022-10-03 21:43 UTC, valfirst commented on docs/modules/user-guides/pages/pipeline-with-proxy.adoc
> +def seleniumVersion = '4.4.0'<5>
`4.5.0` ?

2022-10-04 06:58 UTC, ikalinin1 commented on docs/modules/user-guides/pages/pipeline-with-proxy.adoc
> +                        configuration.profiles=web/docker
```suggestion
                        configuration.profiles=web/docker,web/desktop/chrome

```

2022-10-04 07:31 UTC, valfirst approved these changes

2022-10-04 07:33 UTC, merged