[vividus] Update configuration of ITERATING table transformer
vividus-framework/vividus pull request #3228
Opened 2022-10-05 15:29 UTC by IBrun

2022-10-06 08:14 UTC, ikalinin1 commented on vividus-tests/src/main/resources/story/integration/TableTransformers.story
> +{transformer=ITERATING, startInclusive=0, endInclusive=3}
```suggestion
{transformer=ITERATING, startInclusive=1, endInclusive=3}
```
to verify changed behavior

2022-10-06 08:15 UTC, ikalinin1 commented on vividus-tests/src/main/resources/story/integration/TableTransformers.story
> +Scenario: Update the counter through ITERATING
Please mark the old scenario ad deprecated

2022-10-06 08:21 UTC, ikalinin1 commented on vividus/src/main/java/org/vividus/transformer/IteratingTableTransformer.java
> +            column = Stream.iterate(startInclusive, i -> i <= endInclusive, i -> i + 1)
can we reuse generating code?

2022-10-06 08:23 UTC, ikalinin1 commented on vividus/src/main/java/org/vividus/transformer/IteratingTableTransformer.java
> +            Validate.isTrue(startInclusive >= 0, "'%s' and '%s' values must be non-negative", START_INCLUSIVE,
Why do we need this constraint?

2022-10-06 08:30 UTC, valfirst requested changes

2022-10-06 12:38 UTC, uarlouski commented on vividus/src/main/java/org/vividus/transformer/IteratingTableTransformer.java
> +        List<String> column = Stream.iterate(startInclusive, i -> i <= endInclusive, i -> i + 1)
why not to use IntStream.range() ?

2022-10-06 20:13 UTC, valfirst requested changes

2022-10-06 20:13 UTC, valfirst commented on docs/modules/commons/pages/table-transformers.adoc
> +|value specifying which number to start generating values from. Value should be smaller or equal to `endInclusive` value
```suggestion
|value specifying which number to start generating values from, it should be less than or equal to `endInclusive` value
```

2022-10-06 20:13 UTC, valfirst commented on docs/modules/commons/pages/table-transformers.adoc
> +|threshold value specifying at which number to stop generating values. Value should be greater or equal to `startInclusive` value
```suggestion
|threshold value specifying at which number to stop generating values, it should be greater than or equal to `startInclusive` value
```

2022-10-06 20:13 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/TableTransformers.story
> +{transformer=ITERATING, startInclusive=1, endInclusive=3}
```suggestion
{transformer=ITERATING, startInclusive=1, endInclusive=$\{iterationLimit\}}
```

2022-10-06 20:13 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/VariableTests.story
>  {transformer=ITERATING, limit=1}
```suggestion
{transformer=ITERATING, startInclusive=3, endInclusive=3}
```

that should be enough, no need to add a new scenario

2022-10-06 20:13 UTC, valfirst commented on vividus/src/main/java/org/vividus/transformer/IteratingTableTransformer.java
> +            LOGGER.warn("ExamplesTable property '{}' is deprecated. Use '{}' and '{}' instead", LIMIT, START_INCLUSIVE,
add a note that the deprecated property will be removed in VIVIDUS 0.6.0

2022-10-06 20:13 UTC, valfirst commented on vividus/src/main/java/org/vividus/transformer/IteratingTableTransformer.java
> +            Validate.isTrue(endInclusive >= startInclusive, "'%s' value must be smaller or equal to '%s' value",
```suggestion
            Validate.isTrue(endInclusive >= startInclusive, "'%s' value must be less than or equal to '%s' value",
```

2022-10-10 11:02 UTC, valfirst approved these changes

2022-10-10 15:32 UTC, uarlouski approved these changes

2022-10-10 15:36 UTC, ikalinin1 approved these changes

2022-10-10 15:39 UTC, merged