[docs] Document FROM_JSON transformer
vividus-framework/vividus pull request #3230
Opened 2022-10-06 15:00 UTC by uarlouski

2022-10-06 20:00 UTC, valfirst requested changes

2022-10-07 08:48 UTC, ikalinin1 approved these changes

2022-10-07 08:52 UTC, valfirst requested changes

2022-10-07 08:52 UTC, valfirst commented on docs/modules/plugins/pages/plugin-rest-api.adoc
> += Table Transformers
here should be a link to glossary

2022-10-07 08:52 UTC, valfirst commented on docs/modules/plugins/pages/plugin-rest-api.adoc
> +columns=column_name=json_path;column_name=json_path
```suggestion
columns=column_name_1=json_path_1;column_name_2=json_path_2
```

2022-10-07 08:52 UTC, valfirst commented on docs/modules/plugins/pages/plugin-rest-api.adoc
> +{transformer=FROM_JSON, url=https://fakedata.io/users, columns=fname=$..firstName;lname=$..lastName}
```suggestion
{transformer=FROM_JSON, url=https://data-provider/users, columns=fname=$..firstName;lname=$..lastName}
```

2022-10-07 09:17 UTC, valfirst commented on docs/modules/plugins/pages/plugin-rest-api.adoc
> += Table Transformers
```suggestion
== xref:ROOT:glossary.adoc#_table_transformer[Table Transformers]
```

2022-10-07 09:20 UTC, valfirst approved these changes

2022-10-07 09:21 UTC, merged