[extension-selenium] Disable possibility to modify search visibility …
vividus-framework/vividus pull request #3258
Opened 2022-10-13 12:24 UTC by ikalinin1

…for "appear/disappear" waiting steps

2022-10-13 12:26 UTC, ikalinin1 commented
relates to #2640

2022-10-13 12:28 UTC, valfirst requested changes

2022-10-13 12:28 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/steps/ui/GenericWaitSteps.java
> +            "The step supports locators with VISIBLE visibility settings only. The locator is `%s`", locator);
```suggestion
            "The step supports locators with VISIBLE visibility settings only, but the locator is `%s`", locator);
```

2022-10-14 07:07 UTC, uarlouski approved these changes

2022-10-14 07:28 UTC, valfirst commented on docs/modules/plugins/partials/generic-ui-steps.adoc
> +WARNING: It's forbidden to use visibility type in the locator.
https://github.com/vividus-framework/vividus/pull/3258#discussion_r994577172:
> and add the link to the visibility types

2022-10-14 12:36 UTC, valfirst approved these changes

2022-10-15 15:51 UTC, merged