Exit code
vividus-framework/vividus pull request #3314
Opened 2022-10-31 12:27 UTC by ikalinin1

2022-10-31 12:30 UTC, valfirst requested changes

2022-10-31 12:30 UTC, valfirst commented on .github/workflows/gradle.yml
> +            cat ./exitCode.txt
let's add a kind of assertion here instead of simple print

2022-10-31 12:30 UTC, valfirst commented on docs/modules/commons/partials/exit-code.adoc
> +`build.gradle` file of the test project:
this description doesn't correlate with examples below

2022-11-01 09:32 UTC, valfirst commented
each commit from the PR contains noisy changes in the build system

2022-11-01 09:42 UTC, ikalinin1 commented
> each commit from the PR contains noisy changes in the build system

fixed

2022-11-01 11:09 UTC, valfirst approved these changes

2022-11-01 11:10 UTC, merged