[plugin-shell] Introduce plugin to execute commands using shell
vividus-framework/vividus pull request #3325
Opened 2022-11-04 15:43 UTC by ikalinin1

2022-11-08 09:16 UTC, uarlouski commented on vividus-plugin-shell/src/test/java/org/vividus/shell/ShellStepsTests.java
> +    void testCommandRunUsing(String shellName, String option)
lets make it private?

2022-11-08 09:19 UTC, ikalinin1 commented on vividus-plugin-shell/src/main/java/org/vividus/shell/ShellSteps.java
> +        String error = IOUtils.toString(process.getErrorStream(), StandardCharsets.UTF_8);
Nope

2022-11-08 09:21 UTC, uarlouski commented on vividus-plugin-shell/src/main/java/org/vividus/shell/ShellSteps.java
> +        String output = IOUtils.toString(process.getInputStream(), StandardCharsets.UTF_8);
does IOUtils close the input steams?

2022-11-08 09:23 UTC, uarlouski commented on vividus-plugin-shell/src/main/java/org/vividus/shell/ShellSteps.java
> +        String error = IOUtils.toString(process.getErrorStream(), StandardCharsets.UTF_8);
I just thinking about still providing end users with data from streams because it might contain clue on why the script didn't complete in time

2022-11-08 09:35 UTC, ikalinin1 commented on vividus-plugin-shell/src/main/java/org/vividus/shell/ShellSteps.java
> +        String error = IOUtils.toString(process.getErrorStream(), StandardCharsets.UTF_8);
I was also thinking about that and as an alternative I propose to redirect the process output to the files
@valfirst  what do you think?

2022-11-08 12:13 UTC, valfirst requested changes

2022-11-11 14:31 UTC, valfirst requested changes

2022-11-11 14:31 UTC, valfirst commented on vividus-plugin-shell/src/main/resources/vividus-plugin/spring.xml
> +
```suggestion

```

2022-11-11 14:31 UTC, valfirst commented on vividus-plugin-shell/src/main/resources/vividus-plugin/spring.xml
> +    <util:list id="stepBeanNames-Exec" value-type="java.lang.String">
```suggestion
    <util:list id="stepBeanNames-Shell" value-type="java.lang.String">
```

2022-11-15 16:10 UTC, uarlouski approved these changes

2022-11-16 07:27 UTC, valfirst requested changes

2022-11-16 09:32 UTC, valfirst commented on vividus-plugin-shell/build.gradle
> +    testImplementation(group: 'org.junit-pioneer', name: 'junit-pioneer', version: '1.7.1')
```suggestion
    testImplementation(group: 'org.junit-pioneer', name: 'junit-pioneer', version: '1.9.0')
```

2022-11-17 08:19 UTC, uarlouski approved these changes

2022-11-17 16:07 UTC, valfirst approved these changes

2022-11-18 07:50 UTC, merged