[plugin-mobile-app] Add step to perform double tap on element
vividus-framework/vividus pull request #3350
Opened 2022-11-15 09:55 UTC by IBrun

2022-11-15 10:23 UTC, valfirst requested changes

2022-11-15 10:23 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/TouchActions.java
> +        String script = genericWebDriverManager.isAndroid() ? "mobile: doubleClickGesture" : "mobile: doubleTap";
what about tvOS?

2022-11-15 10:23 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/steps/TouchSteps.java
> +        findElementToTap(locator).ifPresent(touchActions::doubleTap);
the validation message in `findElementToTap` may confuse users, it refers to simple `tap`

2022-11-16 12:24 UTC, uarlouski commented on vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/TouchActions.java
> +        });
the action does nothing if the script is empty, should not we throw unsupported platform here?

2022-11-17 08:14 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/TouchActions.java
> +            throw new IllegalArgumentException("The functionality is supported only for Android and iOS platforms");
```suggestion
            throw new IllegalArgumentException("Double tap action is available only for Android and iOS platforms");
```

2022-11-17 08:41 UTC, ikalinin1 approved these changes

2022-11-17 09:36 UTC, valfirst approved these changes

2022-11-17 16:52 UTC, uarlouski approved these changes

2022-11-17 18:26 UTC, merged