[viviuds] Rename fail-fast properties to avoid bdd reference
vividus-framework/vividus pull request #3410
Opened 2022-11-29 14:41 UTC by ikalinin1

2022-11-29 19:24 UTC, valfirst requested changes
Also deprecated properties mapping is missing

2022-11-29 19:24 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +|`engine.batch.fail-fast`
```suggestion
|`batch.fail-fast`
```

2022-11-29 19:24 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +|`engine.story.fail-fast`
```suggestion
|`story.fail-fast`
```

2022-11-29 19:24 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +|`engine.scenario.fail-fast`
```suggestion
|`scenario.fail-fast`
```

2022-11-29 19:50 UTC, valfirst approved these changes

2022-11-30 08:27 UTC, uarlouski approved these changes

2022-11-30 15:02 UTC, merged