Mobile web
vividus-framework/vividus pull request #3435
Opened 2022-12-07 11:39 UTC by ikalinin1

2022-12-07 14:57 UTC, valfirst requested changes

2022-12-07 14:57 UTC, valfirst commented on .github/workflows/gradle.yml
> +      if: matrix.platform == 'macos-latest'
need to use ubuntu to avoid race conditions

2022-12-07 14:57 UTC, valfirst commented on vividus-plugin-browserstack/src/main/resources/properties/profile/browserstack/web/phone/iphone/profile.properties
> +selenium.grid.platform-version=16
it should be a part of `vividus-tests`

2022-12-07 14:57 UTC, valfirst commented on vividus-plugin-browserstack/src/main/resources/properties/profile/browserstack/web/phone/profile.properties
> +selenium.grid.capabilities.bstack\:options.os=
is it expected value?

2022-12-08 21:39 UTC, valfirst requested changes

2022-12-09 07:58 UTC, uarlouski approved these changes

2022-12-09 08:43 UTC, valfirst approved these changes

2022-12-09 11:58 UTC, merged