[engine] Do not allow to overwrite default composite paths
vividus-framework/vividus pull request #3436
Opened 2022-12-07 12:27 UTC by ikalinin1

2022-12-07 13:46 UTC, uarlouski commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +|`engine.composite-paths`
isn't engine too technical for end users?

2022-12-07 14:28 UTC, uarlouski approved these changes

2022-12-07 15:06 UTC, valfirst requested changes

2022-12-07 15:06 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +https://jbehave.org/reference/stable/composite-steps.html[Composite steps] allows to reuse set of actions via step with a custom wording.
```suggestion
https://jbehave.org/reference/stable/composite-steps.html[Composite steps] allow to reuse set of actions via custom steps with own wordings.
```

2022-12-07 15:06 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +. Define composite step:
```suggestion
. Define composite step in `*.steps` file, e.g. `steps/ui/my-app.steps`:
```

2022-12-07 15:06 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +When I click on element located `id(signInButton)`
```suggestion
When I enter `<username>` in field located by `id(username)`
When I enter `<password>` in field located by `id(password)`
When I click on element located by `id(signInButton)`
```

2022-12-07 15:06 UTC, valfirst commented on docs/modules/ROOT/pages/tests-configuration.adoc
> +. Configure composite paths
```suggestion
. Configure paths to files with custom steps
```

2022-12-09 09:16 UTC, valfirst approved these changes

2022-12-09 09:17 UTC, merged