[vividus-mobile-app] Add step to upload file with data to the device
vividus-framework/vividus pull request #3602
Opened 2023-02-01 11:52 UTC by IBrun

2023-02-01 12:44 UTC, valfirst requested changes

2023-02-01 12:44 UTC, valfirst commented on docs/modules/plugins/pages/plugin-mobile-app.adoc
> +.Upload file with image data to the device
please add one more example showing how to save text data

2023-02-01 12:44 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/action/DeviceActions.java
> +    public void pushBinaryData(String deviceFilePath, byte[] data)
```suggestion
    public void pushFile(String deviceFilePath, byte[] data)
```
also javadoc should be reworked

2023-02-01 12:44 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/steps/DeviceSteps.java
> +        LOGGER.info("Uploading file with name `{}` and data to the device at '{}' folder", fileName,
```suggestion
        LOGGER.info("Uploading file with name `{}` to the device at '{}' folder", fileName,
```

2023-02-01 12:44 UTC, valfirst commented on docs/modules/plugins/pages/plugin-mobile-app.adoc
> +* `$fileName` - The name of the uploaded file.
add a reference on how to find/configure folder for upload

2023-02-01 12:44 UTC, valfirst commented on vividus-plugin-mobile-app/src/main/java/org/vividus/mobileapp/steps/DeviceSteps.java
> +        String deviceFilePath = Paths.get(folderForFileUpload, fileName).toString();
please refactor to avoid code duplications

2023-02-01 12:48 UTC, ikalinin1 commented on docs/modules/plugins/pages/plugin-mobile-app.adoc
> +I upload file with name `$fileName` and data `$data` to device
Keyword is missing

2023-02-01 14:22 UTC, ikalinin1 commented on docs/modules/plugins/pages/plugin-mobile-app.adoc
> +Then the image is displayed with the uploaded image
```suggestion
Then image is displayed in gallery
```

2023-02-01 21:11 UTC, valfirst requested changes

2023-02-01 21:11 UTC, valfirst commented on docs/modules/plugins/partials/mobile-upload-folder-info.adoc
> +The destination folder on the device for the uploaded file is configured by `mobile-environment.devic.folder-for-file-upload` property. See more information in the <<mobile_properties,properties sect
```suggestion
The destination folder on the device for the uploaded file is configured by `mobile-environment.device.folder-for-file-upload` property. See more information in the <<mobile_properties,properties section.>>
```

2023-02-02 07:21 UTC, ikalinin1 approved these changes

2023-02-02 08:11 UTC, valfirst approved these changes

2023-02-02 08:40 UTC, uarlouski approved these changes

2023-02-02 10:18 UTC, merged