[vividus] Add new url expressions
vividus-framework/vividus pull request #3814
Opened 2023-04-07 13:54 UTC by PSharuba

2023-04-07 13:57 UTC, PSharuba commented on vividus/src/main/java/org/vividus/expression/UrlExpressionProcessors.java
> +                new SingleArgExpressionProcessor<>("relativeUrl", UrlExpressionProcessors::getRelativeUrl),
Do we need raltiveUrl expression? In already existing steps relativeUrl check actually checks path equality. (In PageSteps.java "Then the page has the relative URL '$relativeURL'" as example)

2023-04-07 14:12 UTC, uarlouski commented on docs/modules/commons/pages/expressions.adoc
> +== Url manipulations
Documentation should be written in a way not coupled to web app steps

2023-04-07 14:12 UTC, uarlouski commented
No integration tests

2023-04-11 08:44 UTC, valfirst requested changes

2023-04-11 08:44 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +== Url manipulations
`Url manipulations` -> `URL parsing`

2023-04-11 08:44 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +=== extractUrlHost
```suggestion
=== `extractHostFromUrl`
```
please check syntax of other similar docs carefully

2023-04-11 08:44 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +Extracts host value from given URL
```suggestion
Extracts host component from the given URL.
```

2023-04-11 08:44 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +#{extractUrlHost(*$url*)}
missing documentation for the input parameters

2023-04-11 08:44 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +Then `#{extractUrlHost(scheme://host/some/path?query)}` is = `host`
put some less generic examples of URL

2023-04-11 08:44 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +.Validate url host
```suggestion
.Validate host component from URL
```

2023-04-11 08:44 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +=== extractUrlPath
see above comments and refactor the docs

2023-04-11 08:44 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +Extracts path value from given URL
is it raw path or decoded path?

2023-04-11 08:44 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +Extracts query value from given URL
is it raw query or decoded query?

2023-04-11 08:44 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/Expressions.story
> +Scenario: Validate url expressions
```suggestion
Scenario: Validate expressions parsing URLs
```

2023-04-11 08:44 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/Expressions.story
> +|extractUrlQuery(${vividus-test-site-url}/windows.html?query=test)|query=test                |
add examples with encoded path and encoded query

2023-04-11 08:44 UTC, valfirst commented on vividus/src/main/java/org/vividus/expression/UrlExpressionProcessors.java
> +@Named
register bean explicitly

2023-04-11 08:44 UTC, valfirst commented on vividus/src/main/java/org/vividus/expression/UrlExpressionProcessors.java
> +        Validate.notNull(urlPath, "URL path component of '%s' is null", url);
why is this validation needed?

2023-04-11 08:44 UTC, valfirst commented on vividus/src/main/java/org/vividus/expression/UrlExpressionProcessors.java
> +        Validate.notNull(urlQuery, "URL query component of '%s' is null", url);
why is this validation needed?

2023-04-11 08:44 UTC, valfirst commented on vividus/src/test/java/org/vividus/expression/UrlExpressionProcessorsTests.java
> +    @InjectMocks private UrlExpressionProcessors processors;
nothing to inject

2023-04-13 07:45 UTC, valfirst requested changes

2023-04-13 07:45 UTC, valfirst commented on docs/modules/commons/pages/expressions.adoc
> +:url-parameter: pass:quotes[*`$url`* - the URL to extract from]
```suggestion
:url-parameter: pass:quotes[*`$url`* - the URL to extract component from.]
```

2023-04-14 12:05 UTC, merged