Init commit
vividus-framework/vividus pull request #3857
Opened 2023-04-19 20:43 UTC by vkepin

2023-04-20 07:53 UTC, valfirst requested changes

2023-04-20 07:53 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetContextSteps.java
> +    // @When("I switch to a new tab")
```suggestion
    // @When("I switch to new tab")
```

2023-04-20 07:53 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/WindowSteps.java
> +    //TODO: rename? tryToCloseCurrentTab(BiConsumer<WebDriver, String> closeExecutor)
yes, rename please

2023-04-20 07:53 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/IWindowsActions.java
> +    // rename? switchToPreviousTab();
yes, rename all methods

2023-04-20 07:53 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/WindowsActions.java
> +// private methods renaming?
yes, full renaming

2023-04-20 07:53 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/ui/web/listener/PerformanceMetricsListener.java
> +    // Should update to tab?
I don't think that's possible, it's an implementation of Selenium interface

2023-04-25 10:38 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetContextSteps.java
> +     * Switch the focus of future browser commands to the new <b>window object</b>.
let's avoid `window` in javadocs and docs

2023-05-19 16:42 UTC, vkepin commented on docs/modules/plugins/pages/plugin-web-app.adoc
>  === Wait for window and switch
update to tab

2023-05-19 16:43 UTC, vkepin commented on docs/modules/plugins/partials/plugin-web-app-steps.adoc
>  Then text `New Window` does not exist
update text in steps

2023-05-30 08:00 UTC, valfirst requested changes

2023-05-30 08:42 UTC, vkepin commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetContextSteps.java
> +                newTab, not(equalTo(currentTab))))
New tab '{770e3411-5e19-4831-8f36-fc76e46a2807}' is found

2023-06-05 07:43 UTC, vkepin commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetContextSteps.java
> +    @Deprecated(since = "0.5.10", forRemoval = true)
add Replacement annotation and remove logging

2023-06-05 07:43 UTC, vkepin commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetContextSteps.java
>      @When("I switch to window with title that $stringComparisonRule `$windowName`")
add Replacement annotation and remove logging

2023-06-09 12:55 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetContextSteps.java
> +                return String.format("switch to the tab where title %s \"%s\"", comparisonRule.name(), title);
good time to switch to `comparisonRule.toString()`

2023-06-09 13:30 UTC, vkepin commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetContextSteps.java
> +        if (descriptiveSoftAssert.assertThat("New tab is found", newTab, not(equalTo(currentTab))))
if I understand correctly, we decided just to simplify the assertion message - remove tab id from the message

2023-06-09 15:09 UTC, uarlouski approved these changes

2023-06-26 10:18 UTC, valfirst requested changes

2023-06-26 10:18 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetContextSteps.java
> +        if (descriptiveSoftAssert.assertThat("New tab is found", newTab, not(equalTo(currentTab))))
it makes sense to replace `assertThat` with `recordAssertion`, since matcher `not(equalTo(currentTab))` doesn't provide any value for users

2023-06-26 10:18 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/WindowSteps.java
> +                not(contains(currentTab)));
see the comment above about using `recordAssertion` instead of `assertThat`

2023-06-26 10:18 UTC, valfirst commented on vividus-plugin-web-app/src/main/resources/steps/defaults/composite.steps
> +!-- Deprecated: 0.7.0, When I attempt to close current tab with possibility to handle alert
it was changed to upper case: `!-- DEPRECATED: `

2023-06-27 10:22 UTC, valfirst approved these changes

2023-06-27 10:23 UTC, valfirst requested changes
Integration tests are failed

2023-06-28 20:48 UTC, valfirst approved these changes

2023-06-28 20:54 UTC, uarlouski approved these changes

2023-06-28 21:10 UTC, merged