Update syntax for the saveNumberOfOpenTabs step
vividus-framework/vividus pull request #3873
Opened 2023-04-21 15:21 UTC by vkepin

2023-04-21 15:48 UTC, vkepin commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetVariableSteps.java
> +    @When("I save number of open tabs to $scopes variable `$variableName`")
maybe remove 'open' at all? -> I save number of tabs to $scopes variable `$variableName` ?

2023-04-23 20:25 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetVariableSteps.java
> +    @When("I save number of open tabs to $scopes variable `$variableName`")
I propose to do renaming (`tab` -> `window`) for all steps and methods at once

2023-04-23 20:28 UTC, valfirst requested changes

2023-04-23 20:28 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetVariableSteps.java
> +    @When("I save number of open tabs to $scopes variable `$variableName`")
let's keep `open tabs`

2023-04-24 20:12 UTC, valfirst requested changes

2023-04-24 20:12 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +==== Save a number of opened tabs to the variable
```suggestion
==== Save the number of opened tabs
```

2023-04-24 20:12 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +This step allows you to save a number of currently opened tabs in the browser.
```suggestion
Saves the number of currently opened tabs in the browser to the variable.
```

2023-04-24 20:12 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +.Save the first table on the page into a variable named 'table'
need to be updated

2023-04-24 20:12 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetVariableSteps.java
>       * A <b>value</b> is everything after the last <b>/</b>. <br>
```suggestion

```

2023-04-24 20:12 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetVariableSteps.java
> +     * Gets an expected <b>value</b> from the <b>number of open tabs</b>
need to be updated (just copy from the docs)

2023-04-24 20:12 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/SetVariableSteps.java
> +     * @param variableName A name under which the value should be saved
align with docs

2023-04-25 11:43 UTC, merged