[engine] Add ability to disable resource loader configuration
vividus-framework/vividus pull request #4150
Opened 2023-07-18 16:49 UTC by draker94

2023-07-19 08:06 UTC, valfirst commented on vividus/src/main/resources/properties/defaults/default.properties
> +bdd.enable-resource-loader-configuration=false
we should keep it turned on in `0.5.X`

2023-07-20 07:05 UTC, valfirst requested changes

2023-07-20 07:05 UTC, valfirst commented on vividus-engine/src/main/resources/org/vividus/engine/spring.xml
> +        <constructor-arg name="enableResourceLoaderConfiguration" value="${bdd.enable-resource-loader-configuration}" />
```suggestion
        <constructor-arg name="enableResourceLoaderConfiguration" value="${engine.dynamic-resource-search-enabled}" />
```

2023-07-20 07:06 UTC, valfirst requested changes

2023-07-20 07:06 UTC, valfirst commented on vividus-engine/src/main/java/org/vividus/resource/TestResourceLoader.java
> +        resourceLoadParameters = enableResourceLoaderConfiguration
also it makes to log some warning, that this feature is deprecated and will be removed in 0.7.0

2023-07-21 07:34 UTC, valfirst approved these changes

2023-07-21 07:48 UTC, uarlouski commented on vividus-engine/src/main/resources/org/vividus/engine/spring.xml
> +        <constructor-arg name="dynamicResourceSearchEnabled" value="${engine.dynamic-resource-search-enabled}" />
it works only because there is only on boolean in the constructor, the args names are not preserved by default, so I would use index for safety

2023-07-21 08:24 UTC, uarlouski approved these changes

2023-07-21 09:30 UTC, merged