[plugin-web-app] Update dropdown steps syntax
vividus-framework/vividus pull request #4228
Opened 2023-08-14 11:58 UTC by PSharuba

2023-08-16 14:05 UTC, valfirst requested changes

2023-08-18 13:32 UTC, valfirst requested changes

2023-08-18 13:32 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/DropdownSteps.java
>                         .map(Select::new);
```suggestion
        return baseValidations.assertElementExists(DROPDOWN, locator).map(Select::new);
```

2023-08-18 13:32 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/DropdownSteps.java
> +                       .map(Select::new);
```suggestion
        return Optional.ofNullable(baseValidations.assertIfElementExists(DROPDOWN, locator)).map(Select::new);
```

2023-08-21 06:38 UTC, uarlouski commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +Then dropdown located by `$locator` contains options: $option
lets remove the space before $options since it doesn't bring any value

2023-08-21 06:56 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +Then dropdown located by `$locator` contains options: $option
```suggestion
Then dropdown located by `$locator` contains options:$options
```

2023-08-21 06:56 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
>  Then dropdown located `$locator` contains options: $option
```suggestion
Then dropdown located `$locator` contains options:$options
```

2023-08-21 15:05 UTC, valfirst requested changes

2023-08-21 15:05 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +Then dropdown located by `$locator` contains options:$option
```suggestion
Then dropdown located by `$locator` contains options:$options
```

2023-08-21 15:05 UTC, valfirst commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +Then dropdown located `$locator` contains options:$option
```suggestion
Then dropdown located `$locator` contains options:$options
```

2023-08-22 14:35 UTC, valfirst approved these changes

2023-08-24 08:05 UTC, uarlouski approved these changes

2023-08-24 08:11 UTC, merged