[plugin-web-app] Update radio button steps syntax
vividus-framework/vividus pull request #4318
Opened 2023-09-07 13:34 UTC by PSharuba

2023-09-07 14:55 UTC, valfirst requested changes

2023-09-09 07:22 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/RadioButtonSteps.java
> +                new Locator(FIELD_NAME, radioOption)).orElse(null);
it's not correct use only fieldName locator, it's doesn't check for `type` of `input`

2023-09-20 12:57 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/RadioButtonSteps.java
> +                        ".//input[@type='radio' and ((@* | text())=%1$s or @id=(//label[text() = '%1$s']/@for))]",
it seems it makes just to introduce a new locator: `radioButton`

2023-09-25 08:10 UTC, valfirst requested changes

2023-09-26 08:04 UTC, valfirst approved these changes

2023-09-26 11:46 UTC, uarlouski approved these changes

2023-09-26 12:01 UTC, valfirst commented on docs/modules/plugins/partials/plugin-web-app-locators.adoc
> +|`radoButton`
```suggestion
|`radioButton`
```

2023-09-26 13:28 UTC, merged