[util] Percent-encode all restricted characters in URL path
vividus-framework/vividus pull request #4386
Opened 2023-09-30 22:47 UTC by draker94

2023-10-02 06:45 UTC, valfirst requested changes
In general, I think the changes should be less aggressive - we need to percent-encode only non-ASCII characters

2023-10-02 06:45 UTC, valfirst commented on vividus-util/src/test/java/org/vividus/util/UriUtilsTests.java
> +        "http://somehost:8080/pa | th?name=bad|value&a=b#fra| gme nt, http://somehost:8080/pa+%7C+th?name=bad%7Cvalue&a=b#fra%7C%20gme%20nt",
I'm not sure it's correct to replace space with `+` we need to conform this change with RFC

2023-10-02 06:45 UTC, valfirst commented on vividus-util/src/test/java/org/vividus/util/UriUtilsTests.java
> +            "https://ad.doubleclick.net/ddm/activity/src%3D5337729%3Btype%3Dbrand0%3Bcat%3Dbrand0%3Bu9%3D%5BCachebuster%5D%3Bu10%3D%5BSPIKA+Locale%5D%3Bu11%3D%5BSPIKA+Brand%5D%3Bu12%3D%5BPage+Path%5D
is `=` required to be percent-encoded?

2023-10-03 11:25 UTC, valfirst requested changes

2023-10-03 11:25 UTC, valfirst commented on vividus-util/src/main/java/org/vividus/util/UriUtils.java
>              String path = StringUtils.repeat(SLASH, indexOfFirstNonSlashChar - 1) + parsedRelativeUrl.getPath();
can we just encode this path? (instead of creating 2 instances of `URI`)

2023-10-06 08:27 UTC, valfirst requested changes
Please, make sure to cover all the changes and branches with unit tests

2023-10-06 16:10 UTC, draker94 commented
> Please, make sure to cover all the changes and branches with unit tests

The exception below can't be covered because we never get `URISyntaxException` in this method (the method already get URI as param and creating URI from path can get to us only `IllegalArgumentException`). But we intercept it to avoid the need to handle this exception in each method call.
https://github.com/vividus-framework/vividus/pull/4386/files#diff-971440b884468d146e7513151e0742bbf01f2b2d0f52fdf3363792cdccfbae9cR329

2023-10-09 08:30 UTC, valfirst approved these changes

2023-10-09 08:45 UTC, uarlouski approved these changes

2023-10-09 09:09 UTC, merged