AEIH-6146 Change the syntax of the steps for Video Steps
vividus-framework/vividus pull request #4474
Opened 2023-10-23 12:36 UTC by TykovkaV

2023-10-26 07:18 UTC, uarlouski commented on docs/modules/plugins/pages/plugin-web-app.adoc
> +_Deprecated syntax (will be removed in VIVIDUS 0.8.0)_:
0.7.0 here and in other places

2023-10-27 08:47 UTC, valfirst approved these changes

2023-10-30 18:35 UTC, valfirst requested changes

2023-10-30 18:35 UTC, valfirst commented on vividus-tests/src/main/resources/story/integration/VideoSteps.story
> +Then пш`${details.currentTime}` is = `${pausedTime}`
```suggestion
Then `${details.currentTime}` is = `${pausedTime}`
```

2023-10-31 07:15 UTC, valfirst approved these changes

2023-10-31 07:15 UTC, merged