Added Syntax of Lifecycle steps in the Glossary Page - issue#4419
vividus-framework/vividus pull request #4523
Opened 2023-11-02 11:43 UTC by Karb101

Kindly review & accept my PR, Thank you in advance.

2023-11-06 09:01 UTC, valfirst requested changes

2023-11-06 09:01 UTC, valfirst commented on docs/modules/ROOT/pages/glossary.adoc
> +*Synonyms*: Lifecycle Steps, Lifecycle Hooks.
```suggestion
== Lifecycle Steps
*Synonyms*: hooks, fixtures.
```

2023-11-07 15:20 UTC, vkepin approved these changes

2023-11-08 08:26 UTC, valfirst approved these changes

2023-11-08 08:27 UTC, merged