[xray-exporter] Skip test case update if its already up to date in JIRA
vividus-framework/vividus pull request #4753
Opened 2024-01-25 10:27 UTC by uarlouski

2024-01-25 12:33 UTC, valfirst requested changes

2024-01-25 12:41 UTC, uarlouski commented on vividus-facade-jira/src/main/java/org/vividus/jira/databind/JiraEntityDeserializer.java
> +        entity.setRaw(jsonNode.toString());
its a one redundant extra network call if bodies do not match

2024-01-26 07:51 UTC, valfirst requested changes

2024-01-26 07:51 UTC, valfirst commented on vividus-facade-jira/src/main/java/org/vividus/jira/JiraFacade.java
> +    private String requestEntity(String relativeUrl, String entityKey,
```suggestion
    private String retrieveEntity(String relativeUrl, String entityKey,
```

2024-01-26 07:51 UTC, valfirst commented on vividus-facade-jira/src/main/java/org/vividus/jira/databind/JiraEntityDeserializer.java
> +        entity.setStatus(status);
```suggestion
        entity.setStatus(fields.path("status").path("name").asText());
```

2024-01-26 07:51 UTC, valfirst commented on vividus-to-xray-exporter/build.gradle
> +    implementation(group: 'net.javacrumbs.json-unit', name: 'json-unit', version: '3.2.2')
is `vividus-util` sill in use?

2024-01-26 08:22 UTC, valfirst commented on vividus-to-xray-exporter/src/main/java/org/vividus/xray/facade/XrayFacade.java
>              throws IOException, NonEditableIssueStatusException, JiraConfigurationException
```suggestion
            throws NonEditableIssueStatusException
```

2024-01-27 08:52 UTC, merged