Add DisableBrowserFetching property to AppliTools plagin
vividus-framework/vividus pull request #4913
Opened 2024-03-19 12:22 UTC by AndrewCherednichenko1

2024-03-19 12:24 UTC, valfirst requested changes
Please add docs for the new property

2024-03-19 12:24 UTC, valfirst commented on vividus-plugin-applitools/src/test/java/org/vividus/visual/eyes/converter/ExamplesTableToApplitoolsVisualChecksConverterTests.java
> +        Boolean disableBrowserFetching = false;
can be inlined

2024-03-19 13:04 UTC, uarlouski commented on vividus-plugin-applitools/src/main/java/org/vividus/visual/eyes/converter/ExamplesTableToApplitoolsVisualChecksConverter.java
> +    private Boolean disableBrowserFetching;
just primitive boolean?

2024-03-19 13:31 UTC, AndrewCherednichenko1 commented on vividus-plugin-applitools/src/main/java/org/vividus/visual/eyes/converter/ExamplesTableToApplitoolsVisualChecksConverter.java
> +    private Boolean disableBrowserFetching;
Yes, since AppliTools configuration accepts object type

2024-03-19 13:32 UTC, AndrewCherednichenko1 commented on docs/modules/plugins/pages/plugin-applitools.adoc
> +|If `true`, page resources for rendering on the UFG will be fetched from outside of the browser.
Updated, thanks

2024-03-19 13:51 UTC, valfirst commented on docs/modules/plugins/pages/plugin-applitools.adoc
> +|If `true`, page resources for rendering on the UFG will be fetched from outside of the browser.
nope, check https://github.com/vividus-framework/vividus/blob/master/docs/modules/plugins/partials/applitools-configuration.adoc

2024-03-20 07:48 UTC, valfirst commented on docs/modules/plugins/partials/applitools-configuration.adoc
> +** `disable-browser-fetching` - By default, is `false`.  If `true`, page resources for rendering on the UFG will be fetched from outside of the browser.
```suggestion
** `disableBrowserFetching` - By default, is `false`.  If `true`, page resources for rendering on the UFG will be fetched from outside of the browser.
```

2024-03-20 07:51 UTC, uarlouski approved these changes

2024-03-20 08:15 UTC, valfirst approved these changes

2024-03-20 08:16 UTC, merged