[vividus] Use Service Loader for gathering Properties Processors
vividus-framework/vividus pull request #5363
Opened 2024-09-11 14:21 UTC by abudevich

2024-09-12 12:16 UTC, valfirst requested changes

2024-09-12 12:16 UTC, valfirst commented on vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java
> -        try (VaultStoredPropertiesProcessor vaultProcessor = new VaultStoredPropertiesProcessor(properties))
we still need to close `VaultStoredPropertiesProcessor`

2024-09-12 12:16 UTC, valfirst commented on vividus/src/main/java/org/vividus/configuration/DelegatingPropertiesProcessor.java
> +        this.propertiesProcessors = Lists.newArrayList(propertiesProcessors);
no reason to convert to list, `Iterable` can be used

2024-09-12 12:33 UTC, abudevich commented on vividus-engine/src/main/java/org/vividus/configuration/PropertiesProcessor.java
> + * Copyright 2019-2024 the original author or authors.
due to moving this file I have exception during build:
`Execution failed for task ':vividus-engine:spotlessJavaCheck'.`

2024-09-12 14:34 UTC, valfirst requested changes

2024-09-12 14:34 UTC, valfirst commented on vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java
> +            if (processor instanceof VaultStoredPropertiesProcessor)
`ConfigurationResolver` should know nothing about particular implementations of `PropertiesProcessor`, it should be designed in this way:
- `PropertiesProcessor` should inherit `Closeable` interface
- `PropertiesProcessor` should have default empty implementation of `close()`
- `DelegatingPropertiesProcessor` in its `close` method should invoke `close` for each delegate
- `DelegatingPropertiesProcessor` instance should be used with `try-with-resources`

2024-09-12 14:38 UTC, valfirst reviewed
Since the approach is changed, `processProperty` method should be moved from `PropertiesProcessor` interface to `AbstractPropertiesProcessor` class

2024-09-13 08:24 UTC, valfirst requested changes

2024-09-13 08:24 UTC, valfirst commented on vividus/src/main/java/org/vividus/configuration/DelegatingPropertiesProcessor.java
> +            catch (IOException e)
just throw `IOException`

2024-09-13 08:24 UTC, valfirst commented on vividus/src/main/java/org/vividus/configuration/VaultStoredPropertiesProcessor.java
>  {
it should be updated to remove `implements Closeable`

2024-09-13 12:23 UTC, valfirst approved these changes

2024-09-13 12:24 UTC, merged