[plugin-web-app] Add step to check element presence in viewport
vividus-framework/vividus pull request #5590
Opened 2024-12-11 10:56 UTC by uarlouski

2024-12-11 11:39 UTC, valfirst requested changes

2024-12-11 11:39 UTC, valfirst commented on vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/steps/ScrollSteps.java
> +    @Deprecated(since = "0.6.0", forRemoval = true)
```suggestion
    @Deprecated(since = "0.6.15", forRemoval = true)
```

2024-12-11 11:39 UTC, valfirst commented on vividus-plugin-web-app-playwright/src/main/java/org/vividus/ui/web/playwright/steps/ElementSteps.java
> +                is(presence == ViewportPresence.IS));
how does assertion message look like?

2024-12-12 07:04 UTC, uarlouski commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/ElementSteps.java
> +            messageConsumer.accept(message);
looks super awkward

2024-12-12 07:56 UTC, valfirst requested changes

2024-12-12 07:56 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/ElementSteps.java
> +        List<WebElement> elements = baseValidations.assertNumberOfElementsFound("Element to check", locator, 1,
use:
`org.vividus.steps.ui.validation.IBaseValidations#assertElementExists(java.lang.String, org.vividus.selenium.locator.Locator)`

2024-12-12 07:56 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/ElementSteps.java
> +                return (rect.top >= 0 && rect.top <= windowHeight) || (rect.bottom > 0 && rect.bottom <= windowHeight);
I guess such script already exists, we should re-use it

2024-12-12 07:56 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/steps/ui/web/ElementSteps.java
> +            boolean inViewport = javascriptActions.executeScript(script, elements.get(0));
in order to avoid copy-pasted logic it makes sense to introduce abstraction, like, `ScrollActions` and `ScrollValidations`

2024-12-12 11:22 UTC, valfirst requested changes

2024-12-12 11:22 UTC, valfirst commented on vividus-extension-web-app/src/main/java/org/vividus/ui/web/validation/ScrollValidations.java
> +    public void assertElementIsInViewport(T element, ViewportPresence presence)
```suggestion
    public void assertElementPositionAgainstViewport(T element, ViewportPresence presence)
```

2024-12-12 13:02 UTC, valfirst approved these changes

2024-12-12 13:02 UTC, merged