Add new parameter 'byRowNumbers' in FILTERING transformer
vividus-framework/vividus pull request #827
Opened 2020-08-17 13:11 UTC by AlenaBudevich

2020-08-17 13:33 UTC, valfirst commented on vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/FilteringTableTransformer.java
> +    private static final String BY_ROW_NUMBERS_PROPERTY = "byRowNumbers";
`byRowIndexes` ?

2020-08-17 13:38 UTC, valfirst commented on vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/FilteringTableTransformer.java
> +                    .map(Integer::valueOf).map(list::get).collect(Collectors.toList());
`.mapToInt(Integer::parseInt).`

2020-08-19 13:50 UTC, valfirst approved these changes

2020-08-19 14:02 UTC, uarlouski requested changes
All the docs data should go as a separate commit except the part explaining byRowIndexes

2020-08-19 14:03 UTC, uarlouski commented on vividus-bdd-engine/src/main/java/org/vividus/bdd/transformer/FilteringTableTransformer.java
> +                    .mapToObj(list::get).collect(Collectors.toList());
please align in tree-like view

2020-08-19 19:08 UTC, valfirst approved these changes

2020-08-19 20:02 UTC, ikalinin1 approved these changes

2020-08-19 20:06 UTC, merged