Fix NPE when browser session starting in before story
vividus-framework/vividus pull request #862
Opened 2020-08-27 15:46 UTC by ikalinin1

2020-08-27 16:00 UTC, valfirst requested changes

2020-08-27 16:00 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/bdd/monitor/ScreenshotOnFailureMonitor.java
> +        return Optional.ofNullable(bddRunContext.getRunningStory())
when can `runningStory` be `null`?

2020-08-27 16:00 UTC, valfirst commented on vividus-plugin-web-app/src/main/java/org/vividus/bdd/monitor/ScreenshotOnFailureMonitor.java
> +                       .map(RunningScenario::getScenario)
similar here: if `runningScenario` is not `null`, will `scenario` ever be `null`?

2020-08-28 07:16 UTC, valfirst approved these changes

2020-08-28 08:04 UTC, uarlouski approved these changes

2020-08-28 10:18 UTC, merged