Add new step When I wait for presence of element by  with polling int…
vividus-framework/vividus pull request #876
Opened 2020-09-01 10:04 UTC by AlenaBudevich

…erval  retrying retryTimes times stepsToExecute

2020-09-01 12:16 UTC, valfirst requested changes

2020-09-01 12:16 UTC, valfirst commented on vividus-util/src/main/java/org/vividus/util/wait/Waiter.java
> +                ? System.currentTimeMillis() <= endTime : counter < pollingRetries));
I think it makes sense to have 2 implementations of waiter:
- duration based
- retry times based

in this case logic won't be mixed up

2020-09-01 12:16 UTC, valfirst commented on vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/JsonResponseValidationStepsTests.java
> +        if (withPollingInterval)
there should be 2 unit tests, such `if`-s can't be used in unit tests

2020-09-01 12:16 UTC, valfirst commented on vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/JsonResponseValidationSteps.java
> +            + "$stepsToExecute")
```java
When I wait for presence of element by `$jsonPath` with `$pollingInterval` polling interval retrying $retryTimes times$stepsToExecute
```

2020-09-01 12:16 UTC, valfirst commented on vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/JsonResponseValidationSteps.java
> +            + "$stepsToExecute")
also please add docs for new step

2020-09-01 12:16 UTC, valfirst commented on vividus-util/src/main/java/org/vividus/util/wait/Waiter.java
> +    private final int pollingRetries;
`pollingRetries` -> `retryTimes` - to keep naming consistency

2020-09-01 18:19 UTC, uarlouski commented on docs/modules/plugins/pages/plugin-rest-api.adoc
> +Execute a specified amount of `retries` using `polling interval` of time until HTTP response body contains an element by the specified `JSON path`.
execute what? :)

2020-09-01 18:27 UTC, AlenaBudevich commented on docs/modules/plugins/pages/plugin-rest-api.adoc
> +Execute a specified amount of `retries` using `polling interval` of time until HTTP response body contains an element by the specified `JSON path`.
steps :)

2020-09-02 12:25 UTC, valfirst commented on vividus-plugin-rest-api/src/test/java/org/vividus/bdd/steps/api/JsonResponseValidationStepsTests.java
> +        verify(stepsToExecute, atMost(retryTimes)).execute(Optional.empty());
I believe you can check exact number of invocations here

2020-09-02 19:39 UTC, uarlouski commented on vividus-util/src/main/java/org/vividus/util/wait/DurationBasedWaiter.java
> +    public <T, E extends Exception> T wait(FailableSupplier<T, E> valueProvider, Predicate<T> stopCondition) throws E
add override annotation for both waiters

2020-09-07 07:05 UTC, uarlouski approved these changes

2020-09-07 07:19 UTC, valfirst approved these changes

2020-09-07 08:05 UTC, ikalinin1 approved these changes

2020-09-07 08:19 UTC, merged