[extension-selenium] Validate search context before search
vividus-framework/vividus pull request #938
Opened 2020-09-14 10:11 UTC by ikalinin1

2020-09-14 11:06 UTC, valfirst requested changes

2020-09-14 11:06 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/ui/action/search/AbstractElementAction.java
> +    public static final String NOT_SET_CONTEXT = "Unable to locate elements, because search context is not set";
it's better to move it to interface

2020-09-15 07:57 UTC, valfirst approved these changes

2020-09-15 08:12 UTC, uarlouski approved these changes

2020-09-15 08:46 UTC, merged