[extension-selenium] Do not wait for elements in assert element numbe…
vividus-framework/vividus pull request #980
Opened 2020-10-02 16:14 UTC by uarlouski

…r verifications

2020-10-02 19:30 UTC, valfirst requested changes

2020-10-02 19:43 UTC, uarlouski commented on vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/validation/BaseValidations.java
> +            locator.getSearchParameters().setWaitForElement(false);
Hmm I assumed that all steps that check element number on screen should not wait for them, for this purpose we have wait steps

2020-10-03 09:43 UTC, ikalinin1 commented on vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/validation/BaseValidations.java
> +            locator.getSearchParameters().setWaitForElement(false);
I propose to pass this as an option via locator, for example : id(someId):a:nw
or event id(someId):a:wf(PT1S)

2020-10-03 16:44 UTC, uarlouski commented on vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/validation/BaseValidations.java
> +            locator.getSearchParameters().setWaitForElement(false);
Please file a ticket for this improvement :)

2020-10-03 20:30 UTC, valfirst requested changes

2020-10-03 20:30 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/validation/BaseValidations.java
> +                if (ComparisonRule.EQUAL_TO == comparisonRule)
we need to add `LESS_THAN_OR_EQUAL_TO` to this condition as well

2020-10-03 20:30 UTC, valfirst commented on vividus-extension-selenium/src/main/java/org/vividus/bdd/steps/ui/validation/BaseValidations.java
> +                isTrue(ComparisonRule.LESS_THAN != comparisonRule, "Number of elements can not be negative");
"Invalid input rule: the number of elements can not be less than 0"

2020-10-05 07:26 UTC, valfirst approved these changes

2020-10-05 10:42 UTC, ikalinin1 approved these changes

2020-10-05 12:57 UTC, merged